import { html,$,$$,toast,makeRange,makeSelect,makeColor,filePicker } from './helpers.js'
import { makeGifProject } from '../data/defaults.js'
import { BUILTIN_TRANSITIONS,SCENE_IN,SCENE_OUT,TEXT_IN,TEXT_OUT,BORDERS,DECORATIONS,BLEND_MODES,labelOf } from '../data/effects.js'
import { getGLTransitionCatalog } from '../core/glTransitions.js'
import { HistoryManager } from '../core/history.js'
import { uid,deepClone,fileToDataUrl,downloadBlob,debounce,bytesText,loadImage } from '../core/utils.js'
import { renderGifFrame } from '../core/gifRenderer.js'
import { exportOptimizedGif } from '../core/gifExport.js'
import { decodeAnimatedFile } from '../core/animatedDecode.js'
import { putProject,getAssets,putAsset,deleteAsset } from '../core/storage.js'
import { saveProjectFile,loadProjectFile } from '../core/project.js'
import { fontRegistry,fontOptions } from '../core/fontRegistry.js'
import { drawBorder } from '../core/borderEngine.js'
import { drawDecoration } from '../core/decorEngine.js'
import { renderSceneTransition,makeTransitionSample } from '../core/transitionEngine.js'
import { PATTERN_OPTIONS, GRADIENT_PRESETS } from '../core/backgroundEngine.js'

const GL_CATALOG=getGLTransitionCatalog()
const ALL_TRANSITIONS=[...BUILTIN_TRANSITIONS.map(([id,label,category])=>({id,label,category,license:'Built-in'})),...GL_CATALOG]
const STICKER_TYPES=[['heart','하트'],['star','별'],['sparkle','스파클'],['bow','리본'],['cloud','구름'],['flower','꽃'],['diamond','다이아'],['moon','달'],['bubble','버블'],['dot','도트']]


export function createGifEditor(root,{project:initial=null,id='autosave-gif',onHome}){
  let project=initial?deepClone(initial):makeGifProject(),activeTab='scenes',playing=false,raf=0,startTime=0,destroyed=false,overlayAssets=[],previewLoops=new Set()
  const history=new HistoryManager(100),autosave=debounce(()=>putProject(id,project).catch(console.warn),600)
  migrate()
  function migrate(){project.version='2.3.0';project.output=project.output||{size:180,fps:10,colors:128,maxBytes:1900000,circle:true};project.output.maxBytes=Math.min(project.output.maxBytes||1900000,1900000);project.output.lockSize=true;project.background=project.background||{type:'gradient',gradientType:'linear',colorA:'#cbc3ff',colorB:'#ffd4e6',colorC:'#fff3fa',angle:135,stopA:0,stopB:52,stopC:100,hue:0,preset:'custom'};project.background.stopA=project.background.stopA??0;project.background.stopB=project.background.stopB??52;project.background.stopC=project.background.stopC??100;project.background.hue=project.background.hue??0;project.background.preset=project.background.preset||'custom';project.border={type:'sparkle-cluster',width:6,size:100,offset:0,colorA:'#fff',colorB:'#9b8cff',speed:1,...(project.border||{})};project.border.size=project.border.size??100;project.border.offset=project.border.offset??0;project.decoration={type:'sparkles',amount:18,color:'#fff',color2:'#d7c7ff',speed:1,...(project.decoration||{})};for(const s of project.scenes||[]){s.transform=s.transform||{x:0,y:0,scale:1,rotation:0};s.fit=s.fit||'cover';s.layers=s.layers||[];s.transition=normalizeTransition(s.transition);s.transitionDuration=s.transitionDuration??.45;s.inEffect=s.inEffect||'none';s.outEffect=s.outEffect||'none';s.inDuration=s.inDuration??.25;s.outDuration=s.outDuration??.25;s.loadStatus=s.loadStatus||'ready';s.text=s.text||deepClone(project.text);s.text.animationIn=normalizeTextIn(s.text.animationIn);s.text.animationOut=normalizeTextOut(s.text.animationOut);for(const l of s.layers){l.kind=l.kind||'media';l.start=l.start??0;l.end=l.end??s.duration??1.5;l.transform=l.transform||{x:0,y:0,scale:1,rotation:0};l.inEffect=l.inEffect||'fade';l.outEffect=l.outEffect||'fade';l.inDuration=l.inDuration??.2;l.outDuration=l.outDuration??.2;l.visible=l.visible!==false;l.opacity=l.opacity??1;l.blend=l.blend||'screen'}}}
  function normalizeTransition(v){if(!v)return'builtin:fade';if(v.startsWith?.('gl:')||v.startsWith?.('builtin:'))return v;const map={fade:'builtin:fade','cross-fade':'builtin:fade','blur-fade':'builtin:blur-cross','heart-reveal':'builtin:heart-open','star-reveal':'builtin:star-open','pixel-dissolve':'builtin:pixel-grid','sparkle-burst':'builtin:sparkle-burst'};return map[v]||'builtin:fade'}
  function normalizeTextIn(v){const map={'soft-fade':'fade','scale-in':'scale','rotate-in':'rotate','blur-in':'blur','neon-in':'neon','sparkle-in':'sparkle','letter-in':'letter-pop'};return map[v]||v||'fade'}
  function normalizeTextOut(v){const map={'soft-fade-out':'fade','scale-out':'scale','blur-out':'blur','neon-off':'neon','sparkle-out':'sparkle','scatter-out':'scatter','rotate-out':'rotate'};return map[v]||v||'fade'}

  root.innerHTML=`<div class="studio gif-studio-v2"><header class="topbar"><div class="topbar-left"><button class="icon-btn" data-act="home">←</button><div class="studio-title"><b>Profile Motion Studio</b><span>v2.3 · Border & Gradient Update</span></div></div><div class="topbar-center"><button data-act="addScene">+ Scene</button><button data-act="undo">↶ Undo</button><button data-act="redo">↷ Redo</button><button data-act="saveProject">프로젝트 저장</button><button data-act="loadProject">불러오기</button></div><div class="topbar-right"><span id="gif-size-badge" class="size-badge">2MB 제한</span><button class="primary" data-act="exportGif">GIF ≤ 2MB 저장</button></div></header>
  <main class="gif-grid"><aside class="tool-rail gif-tools">${[['scenes','▤','씬'],['transitions','⇄','씬 전환'],['text','T','글씨'],['background','▧','배경'],['border','◉','테두리'],['decor','✦','장식'],['overlays','▧','외부효과'],['draw','✎','그리기']].map(([k,i,n])=>`<button data-tab="${k}" class="${k===activeTab?'active':''}"><i>${i}</i><span>${n}</span></button>`).join('')}</aside>
  <aside class="panel left-panel"><div id="gif-panel"></div></aside>
  <section class="gif-center"><div class="gif-preview-toolbar"><button data-act="play">▶ 재생</button><button data-act="stop">■ 정지</button><label><input type="checkbox" id="loopCheck" ${project.loop?'checked':''}> 반복</label><span id="timeReadout">0.00s</span><span id="previewStatus" class="preview-status">🟡 준비 중</span></div><div class="gif-preview-wrap"><canvas id="gif-canvas" width="520" height="520"></canvas><div class="circle-guide"></div></div><div class="gif-hint">Scene 이미지/움짤은 Canvas에서 드래그 이동 · 오른쪽 Inspector에서 크기/회전 조절</div></section>
  <aside class="panel right-panel"><div class="panel-head"><b>Inspector</b><span id="selectionLabel">Scene</span></div><div id="gif-inspector"></div><div class="divider"></div><div class="panel-head"><b>효과 구분</b></div><div class="legend-box"><span>씬 등장</span><span>씬 퇴장</span><span>씬↔씬 전환</span><span>글씨 등장</span><span>글씨 퇴장</span></div></aside>
  <section class="timeline-shell"><div class="timeline-top"><b>Timeline</b><button data-act="fitTimeline">전체 맞춤</button><span>전환 효과를 Scene 사이 슬롯으로 끌어놓고, 배경 Scene·장식 Scene도 함께 이어붙일 수 있습니다.</span></div><div class="timeline-ruler"><span>0s</span><span>1s</span><span>2s</span><span>3s</span><span>4s+</span></div><div id="gif-timeline" class="gif-timeline v2"></div></section></main></div>`

  const canvas=$('#gif-canvas',root),ctx=canvas.getContext('2d'),panel=$('#gif-panel',root),inspector=$('#gif-inspector',root),timeline=$('#gif-timeline',root)
  const selectedScene=()=>project.scenes.find(s=>s.id===project.selectedSceneId)||project.scenes[0]
  const snapshot=label=>history.push(project,label)
  const changed=(opts={})=>{project.updatedAt=Date.now();autosave();renderTimeline();renderInspector();if(opts.panel!==false)renderPanel();renderStaticPreview();updateBadge()}
  const setProject=p=>{project=deepClone(p);migrate();changed();}

  function bind(){
    $('[data-act="home"]',root).onclick=()=>onHome?.();$('[data-act="addScene"]',root).onclick=addScene;$('[data-act="undo"]',root).onclick=()=>{const p=history.undo(project);if(p)setProject(p)};$('[data-act="redo"]',root).onclick=()=>{const p=history.redo(project);if(p)setProject(p)}
    $('[data-act="play"]',root).onclick=play;$('[data-act="stop"]',root).onclick=stop;$('[data-act="exportGif"]',root).onclick=exportGif;$('[data-act="saveProject"]',root).onclick=()=>saveProjectFile(project);$('[data-act="loadProject"]',root).onclick=async()=>{const f=await filePicker('.prsproj,application/json');if(!f)return;try{snapshot('프로젝트 불러오기');setProject(await loadProjectFile(f))}catch(e){toast(e.message,'error')}}
    $('#loopCheck',root).onchange=e=>{project.loop=e.target.checked;autosave()};$$('.gif-tools button',root).forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;$$('.gif-tools button',root).forEach(x=>x.classList.toggle('active',x===b));renderPanel()})
  }

  function makeBaseScene(name='Scene',duration=2){return{id:uid('scene'),name,duration,transition:'builtin:fade',transitionDuration:.45,inEffect:'none',outEffect:'none',inDuration:.25,outDuration:.25,transform:{x:0,y:0,scale:1,rotation:0},fit:'cover',layers:[],background:deepClone(project.background),text:deepClone(project.text),loadStatus:'ready'}}
  async function addScene(){const f=await filePicker('image/*,video/webm,video/mp4');if(!f)return;await addSceneFile(f)}
  async function addBackgroundStoryScene(){snapshot('배경 Scene 추가');const base=makeBaseScene('배경/글씨 Scene',2.2);base.mediaKind='none';base.imageDataUrl='';base.frames=null;base.text=deepClone(selectedScene()?.text||project.text);base.background=deepClone((selectedScene()?.background)||project.background);project.scenes.push(base);project.selectedSceneId=base.id;changed();toast('배경 + 글씨 Scene을 추가했습니다.','success')}
  async function addSceneFile(file){
    snapshot('Scene 추가');setPreviewStatus('🟡 미디어 불러오는 중');const data=await fileToDataUrl(file),scene={id:uid('scene'),name:file.name,duration:2,transition:'builtin:fade',transitionDuration:.45,inEffect:'none',outEffect:'none',inDuration:.25,outDuration:.25,transform:{x:0,y:0,scale:1,rotation:0},fit:'cover',layers:[],background:deepClone(project.background),text:deepClone(project.text),imageDataUrl:data,mediaKind:file.type.startsWith('video/')?'video':'image',loadStatus:'loading'}
    if(!file.type.startsWith('video/')){const dec=await decodeAnimatedFile(file,360,72);if(dec?.frames?.length>1){scene.frames=dec.frames;scene.sourceFps=dec.fps;scene.duration=Math.min(5,Math.max(1,dec.duration));scene.mediaKind='animated'}}
    try{if(scene.mediaKind!=='video')await loadImage(scene.frames?.[0]||scene.imageDataUrl);scene.loadStatus='ready';setPreviewStatus('🟢 미디어 준비 완료')}catch(e){scene.loadStatus='error';scene.loadError=e.message;setPreviewStatus('🔴 미디어 로드 실패')}project.scenes.push(scene);project.selectedSceneId=scene.id;changed();toast(scene.loadStatus==='ready'?'Scene을 추가했습니다.':'Scene은 추가했지만 미디어 로드를 확인해주세요.',scene.loadStatus==='ready'?'success':'error')
  }

  function renderPanel(){stopPreviewLoops();panel.innerHTML='';({scenes:renderScenes,transitions:renderTransitions,text:renderText,background:renderBackgroundPanel,border:renderBorders,decor:renderDecor,overlays:renderOverlays,draw:renderDraw}[activeTab]||renderScenes)()}
  function title(t,d){panel.append(html('div',{class:'side-title'},[html('h3',{text:t}),html('p',{text:d})]))}

  function renderScenes(){title('Scene','Scene 자체의 등장/퇴장 효과와 사진 위치를 조절합니다. Scene 사이 전환은 별도 탭에서 Drag & Drop합니다. 배경과 글씨만 있는 Story Scene도 만들 수 있습니다.');const add=html('button',{class:'wide primary soft',text:'+ 이미지 / 움짤 / 영상 Scene'}),bgStory=html('button',{class:'wide soft',text:'+ 배경 + 글씨 Scene'});add.onclick=addScene;bgStory.onclick=addBackgroundStoryScene;panel.append(add,bgStory,makeSelect('출력 크기 🔒',[120,150,180,200,256].map(v=>({value:String(v),label:`${v} × ${v}px`})),String(project.output.size||180),v=>{snapshot('출력 크기');project.output.size=Number(v);renderStaticPreview();updateBadge();autosave()}),html('div',{class:'info-box',text:'v2.1에서는 2MB 최적화 중 출력 픽셀 크기를 자동으로 줄이지 않습니다. 선택한 크기가 끝까지 유지됩니다.'}));for(const [i,s] of project.scenes.entries()){const b=html('button',{class:`scene-card ${s.id===project.selectedSceneId?'active':''}`});b.innerHTML=`<span>${i+1}</span><div><b>${s.name}</b><small>${s.loadStatus==='error'?'🔴':s.loadStatus==='loading'?'🟡':'🟢'} ${s.duration.toFixed(2)}초 · ${transitionLabel(s.transition)}</small></div>`;b.onclick=()=>{project.selectedSceneId=s.id;renderPanel();renderTimeline();renderInspector();renderStaticPreview()};panel.append(b)}const sc=selectedScene();if(sc){panel.append(html('div',{class:'effect-split-heading'},[html('b',{text:'씬 등장 효과 미리보기'}),html('span',{text:'SCENE IN'})]),sceneEffectGrid('in',SCENE_IN.filter(x=>x[0]!=='none'),sc),html('div',{class:'effect-split-heading'},[html('b',{text:'씬 퇴장 효과 미리보기'}),html('span',{text:'SCENE OUT'})]),sceneEffectGrid('out',SCENE_OUT.filter(x=>x[0]!=='none'),sc))}}

  function renderTransitions(){
    title('씬↔씬 전환 효과',`오픈소스 GL Transitions ${GL_CATALOG.length}개 + 기본 효과. 카드에 마우스를 올리면 실제 렌더러 미리보기가 재생됩니다. 카드를 Scene 사이 슬롯으로 끌어놓으세요.`)
    const search=html('input',{class:'effect-search',placeholder:'효과 검색: 하트 / zoom / cube / glitch ...'}),cats=html('div',{class:'effect-filter-row'});let filter='전체';['전체','깔끔','귀여움','화려','다이나믹'].forEach(c=>{const b=html('button',{text:c,class:c==='전체'?'active':''});b.onclick=()=>{filter=c;[...cats.children].forEach(x=>x.classList.toggle('active',x===b));draw()};cats.append(b)});panel.append(search,cats);const count=html('div',{class:'effect-count'}),grid=html('div',{class:'transition-card-grid v2'});panel.append(count,grid);search.oninput=draw
    function draw(){grid.innerHTML='';const q=search.value.trim().toLowerCase(),items=ALL_TRANSITIONS.filter(x=>(filter==='전체'||x.category===filter)&&(!q||`${x.label} ${x.name||''}`.toLowerCase().includes(q)));count.textContent=`표시 ${items.length} / 전체 ${ALL_TRANSITIONS.length}`;items.forEach(effect=>grid.append(transitionCard(effect)))}draw()
  }

  function transitionCard(effect){const card=html('div',{class:'transition-effect-card',draggable:'true'}),cv=html('canvas',{width:140,height:76}),meta=html('div',{class:'effect-meta'});meta.innerHTML=`<b>${effect.label}</b><small>${effect.category} · ${effect.license||'Built-in'}${effect.author?` · ${effect.author}`:''}</small>`;card.append(cv,meta);card.addEventListener('dragstart',e=>{e.dataTransfer.setData('application/x-prs-transition',effect.id);e.dataTransfer.effectAllowed='copy'});card.onclick=()=>{const s=selectedScene();if(!s)return;snapshot('씬 전환 적용');s.transition=effect.id;changed({panel:false});previewTransitionOnMain(effect.id)};let running=false,af=0,start=0;card.onmouseenter=()=>{if(running)return;running=true;start=performance.now();const loop=async now=>{if(!running)return;const p=((now-start)%1300)/1300;await drawTransitionPreview(cv,effect.id,p);af=requestAnimationFrame(loop)};af=requestAnimationFrame(loop);previewLoops.add(()=>{running=false;cancelAnimationFrame(af)})};card.onmouseleave=()=>{running=false;cancelAnimationFrame(af);drawTransitionPreview(cv,effect.id,.5)};drawTransitionPreview(cv,effect.id,.5);return card}

  async function drawTransitionPreview(cv,id,p){const a=makeTransitionSample(cv.width,cv.height,'A','#6f63df','#b59dff'),b=makeTransitionSample(cv.width,cv.height,'B','#ec7fa6','#ffd1e1');try{await renderSceneTransition(cv,a,b,id,p)}catch{const c=cv.getContext('2d');c.clearRect(0,0,cv.width,cv.height);c.globalAlpha=1-p;c.drawImage(a,0,0);c.globalAlpha=p;c.drawImage(b,0,0);c.globalAlpha=1}}
  function sampleCanvas(w,h,text,a,b){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,a);g.addColorStop(1,b);x.fillStyle=g;x.fillRect(0,0,w,h);x.fillStyle='#fff';x.font='800 28px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(text,w/2,h/2);return c}

  function renderText(){const s=selectedScene();title('글씨 타이밍 / 디자인','글씨 등장·유지·퇴장을 명확하게 분리합니다. 웹폰트를 추가하면 아래 폰트 선택창에 즉시 나타납니다.');if(!s){panel.append(html('div',{class:'empty-small',text:'Scene을 먼저 추가하세요.'}));return}s.text=s.text||deepClone(project.text);const t=s.text,ta=html('textarea',{rows:2});ta.value=t.content;ta.oninput=()=>{t.content=ta.value;renderStaticPreview();autosave()};panel.append(html('label',{class:'field'},[html('span',{text:'글씨'}),ta]));const fontRow=html('div',{class:'font-actions'}),addF=html('button',{text:'+ 웹폰트/파일 불러오기'}),manage=html('button',{text:'내 폰트'});addF.onclick=importFont;manage.onclick=showFonts;fontRow.append(addF,manage);panel.append(fontRow,makeSelect('폰트',fontOptions(),t.fontFamily||'sans-serif',v=>{snapshot('폰트');t.fontFamily=v;changed({panel:false})}),makeRange({label:'글씨 크기',min:8,max:90,value:t.fontSize||26,onStart:()=>snapshot('글씨 크기'),onInput:v=>{t.fontSize=v;renderStaticPreview();autosave()}}),makeColor('글씨 색',t.color||'#ffffff',v=>{t.color=v;renderStaticPreview();autosave()},()=>snapshot('글씨 색')))
    panel.append(html('div',{class:'mini-heading',text:'시간'}),makeRange({label:'시작 시간',min:0,max:Math.max(.1,s.duration-.05),step:.05,value:t.start||0,suffix:'s',onStart:()=>snapshot('글씨 시작'),onInput:v=>{t.start=Math.min(v,(t.end??s.duration)-.05);renderTimeline();renderStaticPreview();autosave()}}),makeRange({label:'종료 시간',min:.05,max:s.duration,step:.05,value:t.end??s.duration,suffix:'s',onStart:()=>snapshot('글씨 종료'),onInput:v=>{t.end=Math.max(v,(t.start||0)+.05);renderTimeline();renderStaticPreview();autosave()}}),makeRange({label:'등장 길이',min:.05,max:1.5,step:.05,value:t.inDuration||.35,suffix:'s',onStart:()=>snapshot('등장 길이'),onInput:v=>{t.inDuration=v;renderTimeline();autosave()}}),makeRange({label:'퇴장 길이',min:.05,max:1.5,step:.05,value:t.outDuration||.35,suffix:'s',onStart:()=>snapshot('퇴장 길이'),onInput:v=>{t.outDuration=v;renderTimeline();autosave()}}),makeRange({label:'글자별 지연',min:0,max:.4,step:.01,value:t.delayPerLetter||0,suffix:'s',onStart:()=>snapshot('글자 지연'),onInput:v=>{t.delayPerLetter=v;autosave()}}))
    panel.append(html('div',{class:'effect-split-heading'},[html('b',{text:'글씨 등장 효과'}),html('span',{text:'TEXT IN'})]),makeSelect('글씨 등장',TEXT_IN.map(([value,label])=>({value,label})),t.animationIn||'fade',v=>{snapshot('글씨 등장');t.animationIn=v;changed({panel:false})}),textEffectGrid('in',TEXT_IN,t),html('div',{class:'effect-split-heading'},[html('b',{text:'글씨 퇴장 효과'}),html('span',{text:'TEXT OUT'})]),makeSelect('글씨 퇴장',TEXT_OUT.map(([value,label])=>({value,label})),t.animationOut||'fade',v=>{snapshot('글씨 퇴장');t.animationOut=v;changed({panel:false})}),textEffectGrid('out',TEXT_OUT,t))
  }

  function sceneEffectGrid(kind,items,scene){const grid=html('div',{class:'mini-effect-grid'});for(const [id,label] of items){const card=html('button',{class:'mini-effect-card'}),cv=html('canvas',{width:92,height:58}),sp=html('span',{text:label.replace(/^씬 (등장|퇴장) · /,'')});card.append(cv,sp);let af=0,run=false,start=0;const paint=async p=>{const q=deepClone(project);q.border={...(q.border||{}),type:'none'};q.decoration={...(q.decoration||{}),type:'none'};const ss={...deepClone(scene),id:'preview-scene',name:'preview',duration:1.4,imageDataUrl:null,frames:null,mediaKind:'image',background:{type:'gradient',colorA:'#6f63df',colorB:'#f39aba',angle:135},text:{...deepClone(scene.text||project.text),content:''},layers:[],inEffect:kind==='in'?id:'none',outEffect:kind==='out'?id:'none',inDuration:.8,outDuration:.8};q.scenes=[ss];q.output={...(q.output||{}),circle:false,size:92};const tm=kind==='in'?p*.8:.6+p*.8;const out=await renderGifFrame(q,0,tm,0,92);const c=cv.getContext('2d');c.clearRect(0,0,92,58);c.drawImage(out,0,0,92,92,0,-17,92,92)};paint(.5);card.onmouseenter=()=>{run=true;start=performance.now();const loop=async now=>{if(!run)return;await paint(((now-start)%1000)/1000);af=requestAnimationFrame(loop)};af=requestAnimationFrame(loop);previewLoops.add(()=>{run=false;cancelAnimationFrame(af)})};card.onmouseleave=()=>{run=false;cancelAnimationFrame(af);paint(.5)};card.onclick=()=>{snapshot(kind==='in'?'씬 등장':'씬 퇴장');if(kind==='in')scene.inEffect=id;else scene.outEffect=id;changed()};grid.append(card)}return grid}

  function textEffectGrid(kind,items,text){const grid=html('div',{class:'mini-effect-grid text'});for(const [id,label] of items){const card=html('button',{class:'mini-effect-card'}),cv=html('canvas',{width:104,height:58}),sp=html('span',{text:label.replace(/^글씨 (등장|퇴장) · /,'')});card.append(cv,sp);let af=0,run=false,start=0;const paint=async p=>{const q=makeGifProject();q.output.circle=false;q.output.size=104;q.border.type='none';q.decoration.type='none';const tt={...deepClone(text),content:'가나',fontSize:29,x:52,y:52,start:0,end:2,inDuration:.8,outDuration:.8,delayPerLetter:.08,animationIn:kind==='in'?id:'fade',animationOut:kind==='out'?id:'fade'};q.scenes=[{id:'txt',name:'text-preview',duration:2,transition:'builtin:fade',transitionDuration:.3,inEffect:'none',outEffect:'none',transform:{x:0,y:0,scale:1,rotation:0},fit:'cover',layers:[],background:{type:'gradient',colorA:'#39374c',colorB:'#242536',angle:135},text:tt}];const tm=kind==='in'?p*.8:1.2+p*.8;const out=await renderGifFrame(q,0,tm,0,104);const c=cv.getContext('2d');c.clearRect(0,0,104,58);c.drawImage(out,0,0,104,104,0,-23,104,104)};paint(.55);card.onmouseenter=()=>{run=true;start=performance.now();const loop=async now=>{if(!run)return;await paint(((now-start)%1000)/1000);af=requestAnimationFrame(loop)};af=requestAnimationFrame(loop);previewLoops.add(()=>{run=false;cancelAnimationFrame(af)})};card.onmouseleave=()=>{run=false;cancelAnimationFrame(af);paint(.55)};card.onclick=()=>{snapshot(kind==='in'?'글씨 등장':'글씨 퇴장');if(kind==='in')text.animationIn=id;else text.animationOut=id;changed()};grid.append(card)}return grid}

  function renderBackgroundPanel(){
    const s=selectedScene();title('배경 만들기','단색·그라데이션·체크/땡땡이/하트/별 패턴과 직접 첨부한 사진 배경을 사용합니다. Scene별로 서로 다른 배경을 만들 수 있습니다.')
    const target=s?(s.background||(s.background=deepClone(project.background))):project.background
    const modes=html('div',{class:'button-grid'}),c=html('button',{text:'단색'}),g=html('button',{text:'그라데이션'}),p=html('button',{text:'패턴'}),im=html('button',{text:'사진 배경'})
    c.onclick=()=>{snapshot('배경 단색');target.type='color';changed({panel:false});renderPanel()};g.onclick=()=>{snapshot('배경 그라데이션');target.type='gradient';changed({panel:false});renderPanel()};p.onclick=()=>{snapshot('배경 패턴');target.type='pattern';changed({panel:false});renderPanel()};im.onclick=async()=>{const f=await filePicker('image/png,image/jpeg,image/webp,image/gif');if(!f)return;snapshot('배경 사진');target.type='image';target.dataUrl=await fileToDataUrl(f);target.fit='cover';target.scale=1;target.x=0;target.y=0;target.blur=0;target.brightness=0;target.saturation=0;target.hue=target.hue??0;changed({panel:false});renderPanel()};modes.append(c,g,p,im);panel.append(modes)
    if(target.type==='color')panel.append(makeColor('배경색',target.colorA||'#efeaff',v=>{target.colorA=v;renderStaticPreview();autosave()},()=>snapshot('배경색')),makeRange({label:'전체 색조',min:-180,max:180,value:target.hue??0,suffix:'°',onStart:()=>snapshot('배경 색조'),onInput:v=>{target.hue=v;renderStaticPreview();autosave()}}))
    else if(target.type==='gradient'){
      const presetBar=html('div',{class:'mini-heading',text:'파스텔 추천 템플릿'})
      const presetGrid=html('div',{class:'button-grid'})
      GRADIENT_PRESETS.forEach(pr=>{const b=html('button',{text:pr.label});b.onclick=()=>{snapshot('그라데이션 템플릿');Object.assign(target,{type:'gradient',preset:pr.id,gradientType:target.gradientType||'linear',colorA:pr.colorA,colorB:pr.colorB,colorC:pr.colorC,stopA:pr.stopA,stopB:pr.stopB,stopC:pr.stopC,angle:pr.angle,hue:target.hue??0});changed({panel:false})};presetGrid.append(b)})
      panel.append(presetBar,presetGrid,makeSelect('그라데이션 종류',[{value:'linear',label:'선형'},{value:'radial',label:'원형'},{value:'conic',label:'원뿔형'}],target.gradientType||'linear',v=>{target.gradientType=v;renderStaticPreview();autosave()}),makeColor('색 A',target.colorA||'#cbc3ff',v=>{target.colorA=v;target.preset='custom';renderStaticPreview();autosave()},()=>snapshot('배경 색')),makeRange({label:'색 A 위치',min:0,max:95,value:target.stopA??0,suffix:'%',onStart:()=>snapshot('색 A 위치'),onInput:v=>{target.stopA=v;target.preset='custom';if((target.stopB??52)<=v)target.stopB=Math.min(99,v+1);renderStaticPreview();autosave()}}),makeColor('색 B',target.colorB||'#ffd4e6',v=>{target.colorB=v;target.preset='custom';renderStaticPreview();autosave()},()=>snapshot('배경 색')),makeRange({label:'색 B 위치',min:1,max:99,value:target.stopB??52,suffix:'%',onStart:()=>snapshot('색 B 위치'),onInput:v=>{target.stopB=v;target.preset='custom';if((target.stopA??0)>=v)target.stopA=Math.max(0,v-1);if((target.stopC??100)<=v)target.stopC=Math.min(100,v+1);renderStaticPreview();autosave()}}),makeColor('색 C',target.colorC||'#fff3fa',v=>{target.colorC=v;target.preset='custom';renderStaticPreview();autosave()},()=>snapshot('배경 색')),makeRange({label:'색 C 위치',min:2,max:100,value:target.stopC??100,suffix:'%',onStart:()=>snapshot('색 C 위치'),onInput:v=>{target.stopC=v;target.preset='custom';if((target.stopB??52)>=v)target.stopB=Math.max(1,v-1);renderStaticPreview();autosave()}}),makeRange({label:'각도',min:0,max:359,value:target.angle||135,suffix:'°',onStart:()=>snapshot('배경 각도'),onInput:v=>{target.angle=v;renderStaticPreview();autosave()}}),makeRange({label:'전체 색조',min:-180,max:180,value:target.hue??0,suffix:'°',onStart:()=>snapshot('배경 색조'),onInput:v=>{target.hue=v;renderStaticPreview();autosave()}}))
    }
    else if(target.type==='pattern')panel.append(makeSelect('패턴',PATTERN_OPTIONS.map(([value,label])=>({value,label})),target.pattern||'gingham',v=>{target.pattern=v;renderStaticPreview();autosave()}),makeColor('바탕색',target.colorA||'#fff',v=>{target.colorA=v;renderStaticPreview();autosave()},()=>snapshot('패턴 색')),makeColor('무늬 A',target.colorB||'#d7ceff',v=>{target.colorB=v;renderStaticPreview();autosave()},()=>snapshot('패턴 색')),makeColor('무늬 B',target.colorC||'#f8d7e7',v=>{target.colorC=v;renderStaticPreview();autosave()},()=>snapshot('패턴 색')),makeRange({label:'무늬 크기',min:6,max:110,value:target.size||28,onStart:()=>snapshot('패턴 크기'),onInput:v=>{target.size=v;renderStaticPreview();autosave()}}),makeRange({label:'간격',min:0,max:60,value:target.gap??4,onStart:()=>snapshot('패턴 간격'),onInput:v=>{target.gap=v;renderStaticPreview();autosave()}}),makeRange({label:'각도',min:0,max:359,value:target.angle||0,suffix:'°',onStart:()=>snapshot('패턴 각도'),onInput:v=>{target.angle=v;renderStaticPreview();autosave()}}),makeRange({label:'무늬 투명도',min:5,max:100,value:target.opacity??100,suffix:'%',onStart:()=>snapshot('패턴 투명도'),onInput:v=>{target.opacity=v;renderStaticPreview();autosave()}}),makeRange({label:'전체 색조',min:-180,max:180,value:target.hue??0,suffix:'°',onStart:()=>snapshot('배경 색조'),onInput:v=>{target.hue=v;renderStaticPreview();autosave()}}))
    else if(target.type==='image')panel.append(html('div',{class:'info-box',text:target.dataUrl?'✓ 배경 사진 로드 완료':'배경 사진이 없습니다.'}),makeSelect('맞춤',[{value:'cover',label:'채우기(Cover)'},{value:'contain',label:'전체 보이기(Contain)'}],target.fit||'cover',v=>{target.fit=v;renderStaticPreview();autosave()}),makeRange({label:'크기',min:50,max:220,value:(target.scale||1)*100,suffix:'%',onStart:()=>snapshot('배경 크기'),onInput:v=>{target.scale=v/100;renderStaticPreview();autosave()}}),makeRange({label:'X',min:-180,max:180,value:target.x||0,onStart:()=>snapshot('배경 X'),onInput:v=>{target.x=v;renderStaticPreview();autosave()}}),makeRange({label:'Y',min:-180,max:180,value:target.y||0,onStart:()=>snapshot('배경 Y'),onInput:v=>{target.y=v;renderStaticPreview();autosave()}}),makeRange({label:'Blur',min:0,max:24,value:target.blur||0,onStart:()=>snapshot('배경 블러'),onInput:v=>{target.blur=v;renderStaticPreview();autosave()}}),makeRange({label:'밝기',min:-60,max:60,value:target.brightness||0,onStart:()=>snapshot('배경 밝기'),onInput:v=>{target.brightness=v;renderStaticPreview();autosave()}}),makeRange({label:'채도',min:-80,max:80,value:target.saturation||0,onStart:()=>snapshot('배경 채도'),onInput:v=>{target.saturation=v;renderStaticPreview();autosave()}}),makeRange({label:'전체 색조',min:-180,max:180,value:target.hue??0,suffix:'°',onStart:()=>snapshot('배경 색조'),onInput:v=>{target.hue=v;renderStaticPreview();autosave()}}))
    if(s){const sceneBtn=html('button',{class:'wide soft',text:'현재 배경으로 새 Story Scene 만들기'});sceneBtn.onclick=addBackgroundStoryScene;const all=html('button',{class:'wide',text:'현재 배경을 모든 Scene에 적용'});all.onclick=()=>{snapshot('배경 전체 적용');project.background=deepClone(target);for(const sc of project.scenes)sc.background=deepClone(target);changed()};panel.append(sceneBtn,all)}
  }


  function renderBorders(){title('움직이는 원형 테두리','테두리 두께와 별개로 전체 크기를 조절할 수 있습니다. 두께를 올렸을 때 안쪽으로만 두꺼워지는 느낌을 보정하려면 “테두리 크기”와 “반경 오프셋”을 함께 조절하세요.');const grid=html('div',{class:'border-grid-v2'});for(const [id,label] of BORDERS){const card=html('button',{class:`border-preview-card ${project.border.type===id?'active':''}`}),cv=html('canvas',{width:86,height:86}),sp=html('span',{text:label});card.append(cv,sp);let af=0,run=false,start=0;const paint=t=>{const c=cv.getContext('2d');c.clearRect(0,0,86,86);c.fillStyle='#242630';c.beginPath();c.arc(43,43,31,0,Math.PI*2);c.fill();drawBorder(c,{...project.border,type:id},86,t)};paint(.4);card.onmouseenter=()=>{run=true;start=performance.now();const loop=now=>{if(!run)return;paint((now-start)/1000);af=requestAnimationFrame(loop)};af=requestAnimationFrame(loop);previewLoops.add(()=>{run=false;cancelAnimationFrame(af)})};card.onmouseleave=()=>{run=false;cancelAnimationFrame(af)};card.onclick=()=>{snapshot('테두리');project.border.type=id;changed()};grid.append(card)}panel.append(grid,makeRange({label:'테두리 두께',min:1,max:20,value:project.border.width||6,onStart:()=>snapshot('테두리 두께'),onInput:v=>{project.border.width=v;renderStaticPreview();autosave()}}),makeRange({label:'테두리 크기',min:70,max:130,value:project.border.size??100,suffix:'%',onStart:()=>snapshot('테두리 크기'),onInput:v=>{project.border.size=v;renderStaticPreview();autosave()}}),makeRange({label:'반경 오프셋',min:-24,max:24,value:project.border.offset??0,suffix:'px',onStart:()=>snapshot('테두리 오프셋'),onInput:v=>{project.border.offset=v;renderStaticPreview();autosave()}}),makeRange({label:'움직임 속도',min:.1,max:3,step:.1,value:project.border.speed||1,onStart:()=>snapshot('테두리 속도'),onInput:v=>{project.border.speed=v;autosave()}}),makeColor('색상 A',project.border.colorA||'#fff',v=>{project.border.colorA=v;renderStaticPreview();autosave()},()=>snapshot('테두리 색')),makeColor('색상 B',project.border.colorB||'#9b8cff',v=>{project.border.colorB=v;renderStaticPreview();autosave()},()=>snapshot('테두리 색')))}


  function renderDecor(){title('귀여운 장식','전역 장식입니다. 모든 Scene 위에 공통으로 들어가며, Scene별 개별 장식은 “효과 / 장식 레이어” 탭에서 시간 지정과 함께 추가할 수 있습니다.');const grid=html('div',{class:'decor-grid-v2'});for(const [id,label] of DECORATIONS){const card=html('button',{class:project.decoration.type===id?'active':''}),cv=html('canvas',{width:92,height:58}),sp=html('span',{text:label});card.append(cv,sp);let af=0,run=false,start=0;const paint=t=>{const c=cv.getContext('2d');c.clearRect(0,0,92,58);c.fillStyle='#20222a';c.fillRect(0,0,92,58);drawDecoration(c,{...project.decoration,type:id,amount:10},92,t)};paint(.8);card.onmouseenter=()=>{run=true;start=performance.now();const loop=now=>{if(!run)return;paint((now-start)/1000);af=requestAnimationFrame(loop)};af=requestAnimationFrame(loop);previewLoops.add(()=>{run=false;cancelAnimationFrame(af)})};card.onmouseleave=()=>{run=false;cancelAnimationFrame(af);paint(.8)};card.onclick=()=>{snapshot('장식');project.decoration.type=id;changed()};grid.append(card)}panel.append(grid,makeRange({label:'장식 개수',min:0,max:60,value:project.decoration.amount||18,onStart:()=>snapshot('장식 개수'),onInput:v=>{project.decoration.amount=v;renderStaticPreview();autosave()}}),makeRange({label:'움직임 속도',min:.1,max:3,step:.1,value:project.decoration.speed||1,onStart:()=>snapshot('장식 속도'),onInput:v=>{project.decoration.speed=v;autosave()}}),makeColor('장식 색 A',project.decoration.color||'#fff',v=>{project.decoration.color=v;renderStaticPreview();autosave()},()=>snapshot('장식 색')),makeColor('장식 색 B',project.decoration.color2||'#d7c7ff',v=>{project.decoration.color2=v;renderStaticPreview();autosave()},()=>snapshot('장식 색')))}

  async function renderOverlays(){
    title('효과 / 장식 레이어','PNG · GIF · Animated WebP · APNG · WebM · MP4를 가져와 원형 테두리·하트·별·빛 효과를 Scene 위에 올릴 수 있습니다. 또, 정적인 스티커 장식과 움직이는 내장 장식 레이어도 시간 지정과 함께 추가할 수 있습니다.')
    const rowBtns=html('div',{class:'button-grid'}),up=html('button',{class:'primary soft',text:'+ 외부 효과 가져오기'}),addSticker=html('button',{text:'+ 정적 장식'}),addDecor=html('button',{text:'+ 움직이는 장식'});up.onclick=importOverlay;addSticker.onclick=()=>addStickerLayer();addDecor.onclick=()=>addDecorLayer();rowBtns.append(up,addSticker,addDecor);panel.append(rowBtns)
    overlayAssets=await getAssets('overlay').catch(()=>[]);const grid=html('div',{class:'asset-grid'})
    for(const a of overlayAssets){const card=html('div',{class:'asset-card overlay-asset'});card.innerHTML=`<div class="overlay-thumb"><img src="${a.thumb||a.dataUrl}" alt=""></div><span>${a.name}</span><button class="asset-del">×</button>`;card.querySelector('.overlay-thumb').onclick=()=>addOverlayAsset(a);card.querySelector('.asset-del').onclick=async e=>{e.stopPropagation();await deleteAsset(a.id);renderPanel()};grid.append(card)}
    if(!overlayAssets.length)grid.append(html('div',{class:'empty-small',text:'가져온 효과가 없습니다.'}));panel.append(grid)
    const sc=selectedScene();if(!sc)return
    panel.append(html('div',{class:'mini-heading',text:'현재 Scene 효과 레이어'}))
    if(!sc.layers.length)panel.append(html('div',{class:'empty-small',text:'Scene 위에 올라간 외부 효과가 없습니다.'}))
    sc.layers.forEach((l,i)=>{const row=html('div',{class:`overlay-layer-row ${project.selectedLayerId===l.id?'active':''}`});const vis=html('button',{text:l.visible===false?'○':'●'}),name=html('button',{class:'overlay-layer-name',text:l.name}),upb=html('button',{text:'↑'}),down=html('button',{text:'↓'}),del=html('button',{text:'×'});vis.onclick=()=>{snapshot('효과 표시');l.visible=l.visible===false;changed()};name.onclick=()=>{project.selectedLayerId=l.id;renderPanel();renderTimeline();renderStaticPreview()};upb.onclick=()=>{if(i>=sc.layers.length-1)return;snapshot('효과 레이어 순서');[sc.layers[i],sc.layers[i+1]]=[sc.layers[i+1],sc.layers[i]];changed()};down.onclick=()=>{if(i<=0)return;snapshot('효과 레이어 순서');[sc.layers[i],sc.layers[i-1]]=[sc.layers[i-1],sc.layers[i]];changed()};del.onclick=()=>{snapshot('효과 삭제');sc.layers.splice(i,1);if(project.selectedLayerId===l.id)project.selectedLayerId=null;changed()};row.append(vis,name,upb,down,del);panel.append(row)})
    const l=sc.layers.find(x=>x.id===project.selectedLayerId);if(!l)return
    panel.append(html('div',{class:'mini-heading',text:'선택 레이어 조절'}),makeRange({label:'시작 시간',min:0,max:Math.max(.05,sc.duration-.05),step:.05,value:l.start??0,suffix:'s',onStart:()=>snapshot('레이어 시작'),onInput:v=>{l.start=Math.min(v,(l.end??sc.duration)-.05);renderTimeline();renderStaticPreview();autosave()}}),makeRange({label:'종료 시간',min:.05,max:sc.duration,step:.05,value:l.end??sc.duration,suffix:'s',onStart:()=>snapshot('레이어 종료'),onInput:v=>{l.end=Math.max(v,(l.start??0)+.05);renderTimeline();renderStaticPreview();autosave()}}),makeSelect('등장 효과',SCENE_IN.map(([value,label])=>({value,label:label.replace('씬 등장 · ','')})),l.inEffect||'fade',v=>{snapshot('레이어 등장');l.inEffect=v;changed({panel:false})}),makeRange({label:'등장 길이',min:.05,max:1.5,step:.05,value:l.inDuration||.2,suffix:'s',onStart:()=>snapshot('레이어 등장 길이'),onInput:v=>{l.inDuration=v;renderStaticPreview();autosave()}}),makeSelect('퇴장 효과',SCENE_OUT.map(([value,label])=>({value,label:label.replace('씬 퇴장 · ','')})),l.outEffect||'fade',v=>{snapshot('레이어 퇴장');l.outEffect=v;changed({panel:false})}),makeRange({label:'퇴장 길이',min:.05,max:1.5,step:.05,value:l.outDuration||.2,suffix:'s',onStart:()=>snapshot('레이어 퇴장 길이'),onInput:v=>{l.outDuration=v;renderStaticPreview();autosave()}}),makeRange({label:'크기',min:10,max:300,value:(l.transform?.scale||1)*100,suffix:'%',onStart:()=>snapshot('효과 크기'),onInput:v=>{l.transform.scale=v/100;renderStaticPreview();autosave()}}),makeRange({label:'X',min:-180,max:180,value:l.transform?.x||0,onStart:()=>snapshot('효과 X'),onInput:v=>{l.transform.x=v;renderStaticPreview();autosave()}}),makeRange({label:'Y',min:-180,max:180,value:l.transform?.y||0,onStart:()=>snapshot('효과 Y'),onInput:v=>{l.transform.y=v;renderStaticPreview();autosave()}}),makeRange({label:'회전',min:-180,max:180,value:l.transform?.rotation||0,onStart:()=>snapshot('효과 회전'),onInput:v=>{l.transform.rotation=v;renderStaticPreview();autosave()}}),makeRange({label:'불투명도',min:0,max:100,value:(l.opacity??1)*100,suffix:'%',onStart:()=>snapshot('효과 투명도'),onInput:v=>{l.opacity=v/100;renderStaticPreview();autosave()}}),makeRange({label:'재생 속도',min:.1,max:3,step:.1,value:l.speed||1,onStart:()=>snapshot('효과 속도'),onInput:v=>{l.speed=v;renderStaticPreview();autosave()}}),makeSelect('블렌드',BLEND_MODES.map(([value,label])=>({value,label})),l.blend||'screen',v=>{l.blend=v;renderStaticPreview();autosave()}))
    if(l.kind==='sticker')panel.append(makeSelect('장식 종류',STICKER_TYPES.map(([value,label])=>({value,label})),l.stickerType||'heart',v=>{snapshot('정적 장식 종류');l.stickerType=v;changed({panel:false})}),makeColor('색 A',l.color||'#ffffff',v=>{l.color=v;renderStaticPreview();autosave()},()=>snapshot('장식 색')),makeColor('색 B',l.color2||'#ffd8f0',v=>{l.color2=v;renderStaticPreview();autosave()},()=>snapshot('장식 색')),makeSelect('움직임',[{value:'0',label:'정지'},{value:'1',label:'살짝 반짝임'}],l.animated===false?'0':'1',v=>{l.animated=v!=='0';renderStaticPreview();autosave()}))
    if(l.kind==='decor')panel.append(makeSelect('장식 패턴',DECORATIONS.map(([value,label])=>({value,label})),l.decorType||'sparkles',v=>{snapshot('장식 레이어 종류');l.decorType=v;changed({panel:false})}),makeRange({label:'개수',min:1,max:40,value:l.amount||12,onStart:()=>snapshot('장식 레이어 개수'),onInput:v=>{l.amount=v;renderStaticPreview();autosave()}}),makeColor('색 A',l.color||'#ffffff',v=>{l.color=v;renderStaticPreview();autosave()},()=>snapshot('장식 색')),makeColor('색 B',l.color2||'#ffd8f0',v=>{l.color2=v;renderStaticPreview();autosave()},()=>snapshot('장식 색')),makeSelect('모션',[{value:'0',label:'정지'},{value:'1',label:'움직임'}],l.static===true?'0':'1',v=>{l.static=v==='0';renderStaticPreview();autosave()}))
    const fit=html('button',{class:'wide',text:'○ 프로필 원에 자동 맞춤'});fit.onclick=()=>{snapshot('원형 효과 맞춤');l.fit='contain';l.transform={x:0,y:0,scale:1,rotation:0};changed()};panel.append(fit)
  }
  async function importOverlay(){const f=await filePicker('image/*,video/webm,video/mp4');if(!f)return;setPreviewStatus('🟡 효과 불러오는 중');const dataUrl=await fileToDataUrl(f),a={id:uid('overlay'),kind:'overlay',name:f.name,dataUrl,mediaKind:f.type.startsWith('video/')?'video':'image',createdAt:Date.now()};if(!f.type.startsWith('video/')){const dec=await decodeAnimatedFile(f,260,64);if(dec?.frames?.length>1){a.frames=dec.frames;a.sourceFps=dec.fps;a.mediaKind='animated';a.thumb=dec.frames[0]}}await putAsset(a);overlayAssets.push(a);renderPanel();setPreviewStatus('🟢 효과 준비 완료');toast('내 효과 라이브러리에 저장했습니다.','success')}
  function addOverlayAsset(a){const s=selectedScene();if(!s){toast('Scene을 먼저 선택하세요.','error');return}snapshot('외부 효과 추가');const l={id:uid('layer'),kind:'media',name:a.name,dataUrl:a.dataUrl,frames:a.frames,sourceFps:a.sourceFps,mediaKind:a.mediaKind,fit:'contain',transform:{x:0,y:0,scale:1,rotation:0},opacity:1,blend:'screen',speed:1,start:0,end:s.duration,visible:true,inEffect:'fade',outEffect:'fade',inDuration:.2,outDuration:.2};s.layers.push(l);project.selectedLayerId=l.id;changed();setPreviewStatus('🟢 효과가 Canvas에 추가됨');toast('Scene 위에 효과 레이어를 추가했습니다.','success')}
  function addStickerLayer(){const s=selectedScene();if(!s){toast('Scene을 먼저 선택하세요.','error');return}snapshot('정적 장식 추가');const l={id:uid('layer'),kind:'sticker',name:'정적 장식',stickerType:'heart',transform:{x:0,y:0,scale:1,rotation:0},opacity:1,blend:'screen',start:0,end:s.duration,visible:true,inEffect:'fade',outEffect:'fade',inDuration:.2,outDuration:.2,color:'#ffffff',color2:'#ffd8f0',animated:false,size:18};s.layers.push(l);project.selectedLayerId=l.id;changed();toast('정적 장식을 추가했습니다.','success')}
  function addDecorLayer(){const s=selectedScene();if(!s){toast('Scene을 먼저 선택하세요.','error');return}snapshot('움직이는 장식 추가');const l={id:uid('layer'),kind:'decor',name:'장식 레이어',decorType:'sparkles',transform:{x:0,y:0,scale:1,rotation:0},opacity:1,blend:'screen',speed:1,start:0,end:s.duration,visible:true,inEffect:'fade',outEffect:'fade',inDuration:.2,outDuration:.2,color:'#ffffff',color2:'#d7c7ff',amount:12,static:false,areaSize:180};s.layers.push(l);project.selectedLayerId=l.id;changed();toast('움직이는 장식 레이어를 추가했습니다.','success')}

  function renderDraw(){title('그리기','현재 버전에서는 기존 프로젝트의 펜 Stroke를 렌더링합니다. 세밀한 키프레임 드로잉은 다음 마이너 업데이트 대상으로 남겨두었습니다.');panel.append(makeColor('펜 색',project.brush.color||'#fff',v=>project.brush.color=v),makeRange({label:'펜 크기',min:1,max:20,value:project.brush.size||4,onInput:v=>project.brush.size=v}))}

  function renderInspector(){inspector.innerHTML='';const s=selectedScene();if(!s){inspector.append(html('div',{class:'empty-small',text:'Scene을 선택하세요.'}));return}$('#selectionLabel',root).textContent=s.name;inspector.append(makeRange({label:'Scene 길이',min:.4,max:8,step:.05,value:s.duration,suffix:'s',onStart:()=>snapshot('Scene 길이'),onInput:v=>{s.duration=v;s.text.end=Math.min(s.text.end??v,v);for(const l of s.layers)l.end=Math.min(l.end??v,v);changed({panel:false})}}),makeRange({label:'사진 크기',min:20,max:260,value:(s.transform.scale||1)*100,suffix:'%',onStart:()=>snapshot('Scene 크기'),onInput:v=>{s.transform.scale=v/100;renderStaticPreview();autosave()}}),makeRange({label:'사진 X',min:-180,max:180,value:s.transform.x||0,onStart:()=>snapshot('Scene X'),onInput:v=>{s.transform.x=v;renderStaticPreview();autosave()}}),makeRange({label:'사진 Y',min:-180,max:180,value:s.transform.y||0,onStart:()=>snapshot('Scene Y'),onInput:v=>{s.transform.y=v;renderStaticPreview();autosave()}}),makeRange({label:'회전',min:-180,max:180,value:s.transform.rotation||0,onStart:()=>snapshot('Scene 회전'),onInput:v=>{s.transform.rotation=v;renderStaticPreview();autosave()}}))
    inspector.append(html('div',{class:'effect-split-heading'},[html('b',{text:'씬 등장 효과'}),html('span',{text:'SCENE IN'})]),makeSelect('씬 등장',SCENE_IN.map(([value,label])=>({value,label})),s.inEffect||'none',v=>{snapshot('씬 등장');s.inEffect=v;changed({panel:false})}),makeRange({label:'씬 등장 길이',min:.05,max:1.5,step:.05,value:s.inDuration||.25,suffix:'s',onStart:()=>snapshot('씬 등장 길이'),onInput:v=>{s.inDuration=v;autosave()}}),html('div',{class:'effect-split-heading'},[html('b',{text:'씬 퇴장 효과'}),html('span',{text:'SCENE OUT'})]),makeSelect('씬 퇴장',SCENE_OUT.map(([value,label])=>({value,label})),s.outEffect||'none',v=>{snapshot('씬 퇴장');s.outEffect=v;changed({panel:false})}),makeRange({label:'씬 퇴장 길이',min:.05,max:1.5,step:.05,value:s.outDuration||.25,suffix:'s',onStart:()=>snapshot('씬 퇴장 길이'),onInput:v=>{s.outDuration=v;autosave()}}))
    inspector.append(html('div',{class:'mini-heading',text:'Scene 사이 전환'}),html('div',{class:'inspector-transition',text:transitionLabel(s.transition)}),makeRange({label:'전환 길이',min:.1,max:1.5,step:.05,value:s.transitionDuration||.45,suffix:'s',onStart:()=>snapshot('전환 길이'),onInput:v=>{s.transitionDuration=v;autosave()}}))
    const del=html('button',{class:'wide danger-ghost',text:'Scene 삭제'});del.onclick=()=>{snapshot('Scene 삭제');project.scenes=project.scenes.filter(x=>x.id!==s.id);project.selectedSceneId=project.scenes[0]?.id||null;changed()};inspector.append(del)
  }

  function renderTimeline(){timeline.innerHTML='';const row=html('div',{class:'timeline-scenes-v2'});project.scenes.forEach((s,i)=>{const sc=html('button',{class:`timeline-scene-v2 ${s.id===project.selectedSceneId?'active':''}`,draggable:'true'});sc.innerHTML=`<b>Scene ${i+1}</b><span>${s.name}</span><small>${s.duration.toFixed(2)}s</small>`;sc.onclick=()=>{project.selectedSceneId=s.id;renderTimeline();renderInspector();renderPanel();renderStaticPreview()};sc.addEventListener('dragstart',e=>{if(e.dataTransfer.types.includes('application/x-prs-transition'))return;e.dataTransfer.setData('application/x-prs-scene',String(i))});sc.addEventListener('dragover',e=>e.preventDefault());sc.addEventListener('drop',e=>{const from=Number(e.dataTransfer.getData('application/x-prs-scene'));if(Number.isNaN(from)||from===i)return;snapshot('Scene 순서');const[m]=project.scenes.splice(from,1);project.scenes.splice(i,0,m);changed()});row.append(sc);if(i<project.scenes.length-1){const slot=html('div',{class:'transition-slot',text:shortTransition(s.transition)});slot.title='씬 전환 효과를 여기로 끌어오세요';slot.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('application/x-prs-transition')){e.preventDefault();slot.classList.add('dragover')}});slot.addEventListener('dragleave',()=>slot.classList.remove('dragover'));slot.addEventListener('drop',e=>{e.preventDefault();slot.classList.remove('dragover');const tid=e.dataTransfer.getData('application/x-prs-transition');if(!tid)return;snapshot('Scene 전환 Drag&Drop');s.transition=tid;changed();toast(`전환 적용: ${transitionLabel(tid)}`,'success')});slot.onclick=()=>{activeTab='transitions';$$('.gif-tools button',root).forEach(x=>x.classList.toggle('active',x.dataset.tab==='transitions'));project.selectedSceneId=s.id;renderPanel();renderInspector()};row.append(slot)}});timeline.append(row);const s=selectedScene();if(!s)return;const tracks=html('div',{class:'timeline-layer-tracks-v2'});tracks.append(resizableTrack('T 글씨',s.text.start||0,s.text.end??s.duration,s.duration,(a,b)=>{s.text.start=a;s.text.end=b;autosave();renderStaticPreview()}));for(const l of s.layers)tracks.append(resizableTrack(`✦ ${l.name}`,l.start||0,l.end??s.duration,s.duration,(a,b)=>{l.start=a;l.end=b;autosave();renderStaticPreview()}));timeline.append(tracks)}
  function resizableTrack(label,start,end,dur,onChange){const row=html('div',{class:'layer-track v2'}),name=html('span',{text:label}),lane=html('div',{class:'track-lane'}),bar=html('div',{class:'track-bar-v2'}),lh=html('i',{class:'handle left'}),rh=html('i',{class:'handle right'}),txt=html('b',{text:`${start.toFixed(2)}–${end.toFixed(2)}s`});bar.style.left=`${start/dur*100}%`;bar.style.width=`${Math.max(2,(end-start)/dur*100)}%`;bar.append(lh,txt,rh);lane.append(bar);row.append(name,lane);const drag=(which,e)=>{e.preventDefault();snapshot(`${label} 타이밍`);const rect=lane.getBoundingClientRect(),move=ev=>{let t=Math.max(0,Math.min(dur,(ev.clientX-rect.left)/rect.width*dur));if(which==='left')start=Math.min(t,end-.05);else end=Math.max(t,start+.05);bar.style.left=`${start/dur*100}%`;bar.style.width=`${(end-start)/dur*100}%`;txt.textContent=`${start.toFixed(2)}–${end.toFixed(2)}s`;onChange(start,end)},up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);renderPanel()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)};lh.onpointerdown=e=>drag('left',e);rh.onpointerdown=e=>drag('right',e);return row}

  function transitionLabel(id){const b=BUILTIN_TRANSITIONS.find(x=>x[0]===id);if(b)return b[1];return GL_CATALOG.find(x=>x.id===id)?.label||id}
  function shortTransition(id){return transitionLabel(id).replace('씬 전환 · ','').slice(0,12)}
  function stopPreviewLoops(){for(const stop of previewLoops)try{stop()}catch{}previewLoops.clear()}
  async function previewTransitionOnMain(id){const s=selectedScene();if(!s)return;s.transition=id;renderInspector();play()}

  async function renderStaticPreview(time=null){if(playing||destroyed)return;const s=selectedScene(),idx=s?Math.max(0,project.scenes.indexOf(s)):0,t=s?(time??Math.min(.8,s.duration*.45)):0;try{const c=await renderGifFrame(project,idx,t,0,520);ctx.clearRect(0,0,520,520);ctx.drawImage(c,0,0);setPreviewStatus(s?'🟢 미리보기 정상':'🟢 배경 미리보기')}catch(e){console.warn(e);ctx.clearRect(0,0,520,520);ctx.fillStyle='#211f28';ctx.fillRect(0,0,520,520);ctx.fillStyle='#ffb9c9';ctx.font='700 16px sans-serif';ctx.textAlign='center';ctx.fillText('미디어 렌더링 실패',260,245);ctx.font='12px sans-serif';ctx.fillText(String(e.message||e),260,270);setPreviewStatus('🔴 렌더링 오류')}}
  function setPreviewStatus(text){const el=$('#previewStatus',root);if(el)el.textContent=text}
  function totalDuration(){return project.scenes.reduce((a,s)=>a+(s.duration||1.5),0)}
  function locateTime(t){let acc=0;for(let i=0;i<project.scenes.length;i++){const d=project.scenes[i].duration||1.5;if(t<acc+d)return{i,local:t-acc};acc+=d}return{i:Math.max(0,project.scenes.length-1),local:0}}
  function play(){if(!project.scenes.length){toast('먼저 Scene을 추가하세요.','error');return}playing=true;startTime=performance.now();cancelAnimationFrame(raf);tick()}
  function stop(){playing=false;cancelAnimationFrame(raf);renderStaticPreview()}
  async function tick(){if(!playing||destroyed)return;const total=totalDuration(),elapsed=(performance.now()-startTime)/1000,t=project.loop?elapsed%total:Math.min(elapsed,total-.001),loc=locateTime(t),s=project.scenes[loc.i],trans=Math.min(s.transitionDuration??.45,(s.duration||1.5)*.48),tp=loc.local>(s.duration-trans)?(loc.local-(s.duration-trans))/trans:0;try{const c=await renderGifFrame(project,loc.i,loc.local,tp,520);ctx.clearRect(0,0,520,520);ctx.drawImage(c,0,0);$('#timeReadout',root).textContent=`${t.toFixed(2)}s / ${total.toFixed(2)}s`;if(!project.loop&&elapsed>=total){stop();return}}catch(e){console.warn(e)}raf=requestAnimationFrame(tick)}

  async function exportGif(){if(!project.scenes.length){toast('먼저 Scene을 추가하세요.','error');return}const btn=$('[data-act="exportGif"]',root),badge=$('#gif-size-badge',root);btn.disabled=true;try{const result=await exportOptimizedGif(project,{size:project.output.size,fps:project.output.fps,colors:project.output.colors,maxBytes:project.output.maxBytes,onProgress:(p,msg)=>{btn.textContent=`${Math.round(p*100)}% ${msg}`}});downloadBlob(result.blob,'profile-motion-v2.3.gif');badge.textContent=`완료 ${bytesText(result.bytes)} · ${result.size}px · ${result.fps}fps`;badge.className='size-badge ok';toast('GIF 저장 완료','success')}catch(e){badge.textContent='내보내기 실패';badge.className='size-badge bad';toast(e.message,'error')}finally{btn.disabled=false;btn.textContent='GIF ≤ 2MB 저장'}}
  function updateBadge(){const d=totalDuration(),estimated=project.output.size*project.output.size*project.output.fps*Math.max(.3,d)*(project.output.colors/256)*.16,badge=$('#gif-size-badge',root);badge.textContent=`예상 ${bytesText(estimated)} · ${project.output.size}px 🔒 · 제한 1.90MB`;badge.className=`size-badge ${estimated<project.output.maxBytes?'ok':'warn'}`}

  async function importFont(){const choice=prompt('폰트 불러오기\n1 = TTF/OTF/WOFF/WOFF2 파일\n2 = WOFF/WOFF2 URL\n3 = @font-face CSS','1');try{if(choice==='1'){const f=await filePicker('.ttf,.otf,.woff,.woff2,font/*');if(f)await fontRegistry.addFile(f)}else if(choice==='2'){const url=prompt('폰트 직접 URL');if(!url)return;const name=prompt('폰트 이름','Custom WebFont');await fontRegistry.addUrl(url,name)}else if(choice==='3'){const css=prompt('@font-face CSS를 붙여넣으세요. 폰트 라이선스와 CORS를 확인하세요.');if(css)await fontRegistry.addCss(css)}renderPanel();toast('폰트를 불러왔고 선택창에 등록했습니다.','success')}catch(e){toast(`폰트 로드 실패: ${e.message}`,'error')}}
  function showFonts(){const names=fontRegistry.list().map(x=>`${x.builtin?'•':'★'} ${x.name||x.family}`).join('\n');alert(`현재 선택 가능한 폰트\n\n${names}`)}

  function onKey(e){const tag=e.target?.tagName?.toLowerCase();if(['input','textarea','select'].includes(tag)&&!(e.ctrlKey||e.metaKey))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();const p=e.shiftKey?history.redo(project):history.undo(project);if(p)setProject(p)}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();const p=history.redo(project);if(p)setProject(p)}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProjectFile(project)}else if(e.code==='Space'){e.preventDefault();playing?stop():play()}}
  async function init(){bind();window.addEventListener('keydown',onKey);await fontRegistry.init();overlayAssets=await getAssets('overlay').catch(()=>[]);renderPanel();renderTimeline();renderInspector();renderStaticPreview();updateBadge();autosave()}
  init();return{destroy(){destroyed=true;cancelAnimationFrame(raf);stopPreviewLoops();window.removeEventListener('keydown',onKey)}}
}
