export const $=(sel,root=document)=>root.querySelector(sel)
export const $$=(sel,root=document)=>[...root.querySelectorAll(sel)]
export function html(tag,attrs={},children=[]){const e=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else if(k.startsWith('on'))e.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==undefined&&v!==null)e.setAttribute(k,v)}for(const c of Array.isArray(children)?children:[children])e.append(c?.nodeType?c:document.createTextNode(c??''));return e}
export function toast(msg,type='info'){let box=document.querySelector('.toast-stack');if(!box){box=html('div',{class:'toast-stack'});document.body.append(box)}const t=html('div',{class:`toast ${type}`,text:msg});box.append(t);setTimeout(()=>t.classList.add('show'),10);setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),250)},2800)}
export function confirmDialog(msg){return window.confirm(msg)}
export function makeRange({label,min=-100,max=100,step=1,value=0,onInput,onStart,suffix=''}){const wrap=html('label',{class:'control-row'});const top=html('span',{class:'control-label'});top.append(html('span',{text:label}),html('output',{text:`${value}${suffix}`}));const input=html('input',{type:'range',min,max,step,value});input.addEventListener('pointerdown',()=>onStart?.());input.addEventListener('input',e=>{top.querySelector('output').textContent=`${e.target.value}${suffix}`;onInput?.(Number(e.target.value))});wrap.append(top,input);return wrap}
export function makeSelect(label,options,value,onChange){const wrap=html('label',{class:'field'});wrap.append(html('span',{text:label}));const s=html('select');for(const o of options){const v=typeof o==='string'?o:o.value,n=typeof o==='string'?o:o.label;const op=html('option',{value:v,text:n});if(v===value)op.selected=true;s.append(op)}s.addEventListener('change',()=>onChange?.(s.value));wrap.append(s);return wrap}
export function makeColor(label,value,onInput,onStart){const wrap=html('label',{class:'field color-field'});wrap.append(html('span',{text:label}));const input=html('input',{type:'color',value});input.addEventListener('pointerdown',()=>onStart?.());input.addEventListener('input',()=>onInput?.(input.value));wrap.append(input);return wrap}
export function filePicker(accept,multiple=false){return new Promise(resolve=>{const i=document.createElement('input');i.type='file';i.accept=accept;i.multiple=multiple;i.onchange=()=>resolve(multiple?[...i.files]:i.files?.[0]||null);i.click()})}
