import { html, $, $$, toast, makeRange, makeSelect, makeColor, filePicker } from './helpers.js'
import { makePhotoProject } from '../data/defaults.js'
import { PHOTO_PRESETS, PRESET_CATEGORIES, DEFAULT_ADJUSTMENTS } from '../data/presets.js'
import { HistoryManager } from '../core/history.js'
import { uid, deepClone, fileToDataUrl, loadImage, downloadBlob, debounce } from '../core/utils.js'
import { drawImageFit } from '../core/image.js'
import { autoSubject, alphaSubject, magicWand, invertMask, maskToCanvas, maskFromDataUrl, canvasToDataUrl, refineSubjectMask } from '../core/mask.js'
import { pathToMask, snapPointToEdge } from '../core/edge.js'
import { renderPhotoProject } from '../core/photoRenderer.js'
import { putAsset, getAssets, deleteAsset, putProject } from '../core/storage.js'
import { saveProjectFile, loadProjectFile, addFontFromFile, addFontFromUrl, injectFontFaceCss } from '../core/project.js'
import { aiSubjectMask } from '../core/aiSubject.js'
import { LIGHT_PRESETS } from '../core/lighting.js'
import { fontRegistry, fontOptions } from '../core/fontRegistry.js'
import { PATTERN_OPTIONS } from '../core/backgroundEngine.js'
import { optimizePngFixedSize, PHOTO_EXPORT_PRESETS, describeOptimizerResult } from '../core/fixedSizeOptimizer.js'

const ADJUSTMENT_LABELS=[
  ['exposure','노출',-40,40],['brightness','밝기',-50,50],['contrast','대비',-50,50],['saturation','채도',-50,50],['vibrance','생동감',-50,50],
  ['highlights','하이라이트',-60,60],['shadows','그림자',-60,60],['temperature','색온도',-50,50],['tint','Tint',-50,50],['yellowReduce','피부 노란기 감소',0,60],
  ['clarity','클리어리티',-30,40],['sharpen','선명도',0,40],['bloom','Bloom',0,40]
]

const GLOW_PRESETS={
  '소프트 화이트':{innerColor:'#ffffff',outerColor:'#ffffff',innerWidth:4,outerWidth:24,softness:24,opacity:38,brightness:115},
  '화이트 + 시안':{innerColor:'#ffffff',outerColor:'#74f4ff',innerWidth:5,outerWidth:32,softness:26,opacity:52,brightness:135},
  '소프트 민트':{innerColor:'#f8ffff',outerColor:'#8fffd7',innerWidth:4,outerWidth:28,softness:24,opacity:45,brightness:125},
  '아이스 블루':{innerColor:'#ffffff',outerColor:'#9ad9ff',innerWidth:4,outerWidth:30,softness:27,opacity:48,brightness:130},
  '라벤더':{innerColor:'#ffffff',outerColor:'#c5b5ff',innerWidth:4,outerWidth:30,softness:28,opacity:46,brightness:125},
  '핑크 화이트':{innerColor:'#ffffff',outerColor:'#ffc2df',innerWidth:4,outerWidth:28,softness:25,opacity:45,brightness:125},
  '문라이트':{innerColor:'#eaf7ff',outerColor:'#79aaff',innerWidth:3,outerWidth:36,softness:32,opacity:42,brightness:135},
  '오로라':{innerColor:'#ffffff',outerColor:'#80ffe0',innerWidth:5,outerWidth:38,softness:34,opacity:50,brightness:140}
}

export function createPhotoEditor(root,{project:initial=null,id='autosave-photo',onHome}){
  let project=initial?deepClone(initial):makePhotoProject(),activeTab='presets',activeTool='select',compare=false,renderSeq=0,destroyed=false
  let maskEditCanvas=null,maskDrawing=false,moving=null,drawingStroke=null,frameAssets=[],fontAssets=[],edgeSource=null,dragPoint=-1
  const history=new HistoryManager(100),autosave=debounce(()=>putProject(id,project).catch(console.warn),650)

  migrate()
  function migrate(){
    project.version='2.1.0';project.canvas.viewMode=project.canvas.viewMode||'final';project.manualPath=project.manualPath||{mode:'polygon',points:[],closed:false,edgeSnap:true,snapRadius:14,smooth:2};project.maskSettings={tolerance:38,feather:1,expand:4,contract:0,smooth:2,contiguous:true,brushSize:34,brushHardness:75,...(project.maskSettings||{})}
    const legacy=project.glow||{};project.lighting={enabled:false,preset:'내추럴 역광',angle:225,range:92,focus:1.7,rimColor:'#ffffff',rimWidth:Math.min(3,legacy.innerWidth||2),rimSoftness:.55,rimOpacity:Math.min(62,legacy.opacity||48),haloColor:legacy.outerColor||'#dffaff',haloWidth:Math.min(12,legacy.outerWidth||7),haloSoftness:Math.min(12,legacy.softness||7),haloOpacity:legacy.opacity?Math.min(16,legacy.opacity*.25):9,sparkleColor:'#ffffff',sparkleCount:0,sparkleSize:2,sparkleSeed:19,breakup:.12,...(project.lighting||{})}
  }

  root.innerHTML=`<div class="studio photo-studio">
    <header class="topbar"><div class="topbar-left"><button class="icon-btn" data-act="home">←</button><div class="studio-title"><b>Photo Retouch</b><span>v2.1 · Natural Rim Light</span></div></div>
    <div class="topbar-center"><button data-act="upload">사진 업로드</button><button data-act="undo">↶ Undo</button><button data-act="redo">↷ Redo</button><button data-act="compare" class="hold-btn">원본 비교</button><button data-act="saveProject">프로젝트 저장</button><button data-act="loadProject">불러오기</button></div>
    <div class="topbar-right"><button data-act="exportJpg">JPG</button><button class="primary" data-act="exportPng">PNG 저장</button></div></header>
    <main class="editor-grid"><aside class="tool-rail">
      ${[['presets','✨','프리셋'],['adjust','☀','기본보정'],['edge','✒','외곽선'],['lighting','✦','라이팅'],['background','▧','배경'],['frames','▣','프레임'],['text','T','텍스트'],['draw','✎','그리기'],['export','⇩','용량최적화']].map(([k,i,n])=>`<button data-tab="${k}" class="${k===activeTab?'active':''}"><i>${i}</i><span>${n}</span></button>`).join('')}
    </aside><aside class="panel left-panel"><div id="photo-panel"></div></aside>
    <section class="canvas-area"><div class="canvas-toolbar"><span id="canvasInfo">Canvas</span><div class="view-modes"><button data-view="original">원본</button><button data-view="mask">마스크</button><button data-view="edge">외곽선</button><button data-view="rim">Rim</button><button data-view="halo">Halo</button><button data-view="sparkle">Sparkle</button><button data-view="lighting">전체 빛</button><button data-view="final" class="active">최종</button></div><div><button data-act="square">1:1</button><button data-act="circle">○ 원형</button></div></div>
      <div class="canvas-stage" id="photo-stage"><canvas id="photo-canvas"></canvas><div class="drop-hint">사진을 업로드하거나 끌어놓으세요</div></div>
      <div class="statusbar"><span id="toolStatus">선택 도구</span><span>Ctrl+Z Undo · W 마법봉 · P Polygon · C Curve</span><span id="saveStatus">자동 저장</span></div></section>
    <aside class="panel right-panel"><div class="panel-head"><b>Layers</b><button data-act="addText">+ 텍스트</button></div><div id="layer-list" class="layer-list"></div><div class="divider"></div><div class="panel-head"><b>선택 레이어</b></div><div id="layer-props" class="layer-props"></div><div class="divider"></div><div class="panel-head"><b>History</b><span>100단계</span></div><div id="history-list" class="history-list"></div></aside></main></div>`

  const canvas=$('#photo-canvas',root),stage=$('#photo-stage',root),panel=$('#photo-panel',root),layerList=$('#layer-list',root),layerProps=$('#layer-props',root)
  function snapshot(label){history.push(project,label);renderHistory()}
  function changed({panelToo=false}={}){project.updatedAt=Date.now();autosave();scheduleRender();renderLayerList();renderLayerProps();if(panelToo)renderPanel()}
  function setProject(next){project=deepClone(next);migrate();maskEditCanvas=null;edgeSource=null;changed({panelToo:true});renderHistory()}
  function mainLayer(){return project.layers.find(l=>l.role==='main')}
  function selectedLayer(){return project.layers.find(l=>l.id===project.selectedLayerId)}

  function bindTop(){
    $('[data-act="home"]',root).onclick=()=>onHome?.();$('[data-act="upload"]',root).onclick=uploadPhoto
    $('[data-act="undo"]',root).onclick=()=>{const p=history.undo(project);if(p)setProject(p)};$('[data-act="redo"]',root).onclick=()=>{const p=history.redo(project);if(p)setProject(p)}
    const cmp=$('[data-act="compare"]',root);cmp.addEventListener('pointerdown',()=>{compare=true;scheduleRender()});['pointerup','pointerleave'].forEach(ev=>cmp.addEventListener(ev,()=>{compare=false;scheduleRender()}))
    $('[data-act="saveProject"]',root).onclick=()=>saveProjectFile(project);$('[data-act="loadProject"]',root).onclick=async()=>{const f=await filePicker('.prsproj,application/json');if(!f)return;try{snapshot('프로젝트 불러오기');setProject(await loadProjectFile(f));toast('프로젝트를 불러왔습니다.','success')}catch(e){toast(e.message,'error')}}
    $('[data-act="exportPng"]',root).onclick=()=>exportImage('png');$('[data-act="exportJpg"]',root).onclick=()=>exportImage('jpeg')
    $('[data-act="square"]',root).onclick=()=>{snapshot('1:1 캔버스');const s=Math.min(Math.max(project.canvas.width,project.canvas.height),2560);project.canvas.width=project.canvas.height=s;project.maskDataUrl=null;project.manualPath.points=[];maskEditCanvas=null;edgeSource=null;changed();toast('캔버스를 1:1로 변경했습니다. 외곽선은 다시 확인해주세요.')}
    $('[data-act="circle"]',root).onclick=()=>{snapshot('원형 미리보기');project.canvas.circularPreview=!project.canvas.circularPreview;changed()};$('[data-act="addText"]',root).onclick=addTextLayer
    $$('.tool-rail button',root).forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;$$('.tool-rail button',root).forEach(x=>x.classList.toggle('active',x===b));renderPanel()})
    $$('[data-view]',root).forEach(b=>b.onclick=()=>{project.canvas.viewMode=b.dataset.view;$$('[data-view]',root).forEach(x=>x.classList.toggle('active',x===b));scheduleRender()})
  }

  async function uploadPhoto(){const f=await filePicker('image/png,image/jpeg,image/webp');if(f)await setMainPhoto(f)}
  async function setMainPhoto(file){
    const dataUrl=await fileToDataUrl(file),im=await loadImage(dataUrl);snapshot('사진 업로드');const max=2560,scale=Math.min(1,max/Math.max(im.naturalWidth,im.naturalHeight));project.canvas.width=Math.max(256,Math.round(im.naturalWidth*scale));project.canvas.height=Math.max(256,Math.round(im.naturalHeight*scale))
    project.layers=project.layers.filter(l=>l.role!=='main');const layer={id:uid('main'),type:'image',role:'main',name:file.name,visible:true,opacity:1,dataUrl,fit:'cover',cutout:false,transform:{x:0,y:0,scale:1,rotation:0},blend:'source-over'};project.layers.push(layer);project.selectedLayerId=layer.id;project.maskDataUrl=null;project.manualPath.points=[];project.manualPath.closed=false;maskEditCanvas=null;edgeSource=null
    try{const {imageData}=await rasterMain();let transparent=0;for(let i=3;i<imageData.data.length;i+=4)if(imageData.data[i]<245)transparent++;if(transparent>imageData.width*imageData.height*.02){const m=alphaSubject(imageData);project.maskDataUrl=canvasToDataUrl(maskToCanvas(m,imageData.width,imageData.height,1));project.lighting.enabled=true;toast('투명 알파를 감지해 정밀 외곽 마스크를 만들었습니다.','success')}}catch(e){console.warn(e)}
    changed({panelToo:true})
  }
  async function rasterMain(){const l=mainLayer();if(!l)throw new Error('먼저 사진을 업로드해주세요.');const im=await loadImage(l.dataUrl),c=document.createElement('canvas');c.width=project.canvas.width;c.height=project.canvas.height;const ctx=c.getContext('2d',{willReadFrequently:true});drawImageFit(ctx,im,c.width,c.height,l.fit||'cover',l.transform||{});return {canvas:c,imageData:ctx.getImageData(0,0,c.width,c.height)}}

  async function autoSelect(){try{const {imageData}=await rasterMain();snapshot('빠른 자동 전경 초안');const rough=autoSubject(imageData,project.maskSettings.tolerance),m=refineSubjectMask(rough,imageData,{edgeThreshold:30,cleanPasses:1});project.maskDataUrl=canvasToDataUrl(maskToCanvas(m,imageData.width,imageData.height,Math.min(1.2,project.maskSettings.feather)));maskEditCanvas=null;project.lighting.enabled=true;changed();toast('빠른 자동 초안을 만들었습니다. 복잡한 배경은 AI 정밀 인식 또는 Polygon/Curve로 보정해주세요.','success')}catch(e){toast(e.message,'error')}}
  async function aiSelect(button=null){
    const main=mainLayer();if(!main){toast('먼저 사진을 업로드해주세요.','error');return}
    const previous=button?.textContent;
    try{
      if(button){button.disabled=true;button.textContent='AI 모델 준비 중…'}
      snapshot('AI 정밀 캐릭터 인식');
      const mask=await aiSubjectMask(main.dataUrl,project.canvas.width,project.canvas.height,p=>{
        if(!button)return;
        const pct=typeof p?.progress==='number'?` ${Math.round(p.progress)}%`:'';
        button.textContent=`AI 인식 중${pct}`
      });
      const {imageData}=await rasterMain();const refined=refineSubjectMask(mask,imageData,{edgeThreshold:26,cleanPasses:1});project.maskDataUrl=canvasToDataUrl(maskToCanvas(refined,project.canvas.width,project.canvas.height,Math.max(0,Math.min(1.2,project.maskSettings.feather))));
      maskEditCanvas=null;project.lighting.enabled=true;project.canvas.viewMode='edge';changed({panelToo:true});syncViewButtons();
      toast('AI가 캐릭터 외곽선용 마스크 초안을 만들었습니다. 배경 제거가 아니라 Glow 경계 계산에 사용됩니다.','success')
    }catch(e){console.warn(e);toast(`AI 인식 실패: ${e.message}. 빠른 자동/Polygon/Curve 도구는 계속 사용할 수 있습니다.`,'error')}
    finally{if(button){button.disabled=false;button.textContent=previous||'🧠 AI 정밀 캐릭터 인식'}}
  }
  async function useMagicWand(px,py){try{const {imageData}=await rasterMain();snapshot('Magic Wand');const bg=magicWand(imageData,px,py,project.maskSettings.tolerance,project.maskSettings.contiguous),subject=invertMask(bg);project.maskDataUrl=canvasToDataUrl(maskToCanvas(subject,imageData.width,imageData.height,project.maskSettings.feather));maskEditCanvas=null;project.lighting.enabled=true;changed();toast('클릭한 배경색을 기준으로 마스크 초안을 만들었습니다.','success')}catch(e){toast(e.message,'error')}}
  async function ensureMaskCanvas(){if(maskEditCanvas)return maskEditCanvas;const c=document.createElement('canvas');c.width=project.canvas.width;c.height=project.canvas.height;const ctx=c.getContext('2d');if(project.maskDataUrl){const im=await loadImage(project.maskDataUrl);ctx.drawImage(im,0,0,c.width,c.height)}maskEditCanvas=c;return c}
  async function applyManualPath(){if(project.manualPath.points.length<3){toast('외곽선 점을 최소 3개 찍어주세요.','error');return}snapshot('수동 외곽선 적용');const mask=pathToMask(project.manualPath,project.canvas.width,project.canvas.height);project.maskDataUrl=canvasToDataUrl(maskToCanvas(mask,project.canvas.width,project.canvas.height,project.maskSettings.feather));project.manualPath.closed=true;maskEditCanvas=null;project.lighting.enabled=true;activeTool='select';changed({panelToo:true});toast('수동 외곽선을 Glow 마스크로 적용했습니다.','success')}

  function renderPanel(){panel.innerHTML='';({presets:renderPresets,adjust:renderAdjust,edge:renderEdge,lighting:renderLighting,background:renderBackground,frames:renderFrames,text:renderText,draw:renderDraw,export:renderExport}[activeTab]||renderPresets)()}
  function sectionTitle(title,desc){panel.append(html('div',{class:'side-title'},[html('h3',{text:title}),html('p',{text:desc})]))}

  function renderPresets(){sectionTitle('Smart Presets','40+ 프리셋. 먼저 40~60% 강도로 시작한 뒤 미세 조정하세요.');const ai=html('button',{class:'wide primary soft',text:'✨ 사진 분석 후 프리셋 추천'});ai.onclick=recommendPreset;panel.append(ai,makeRange({label:'프리셋 강도',min:0,max:100,value:project.preset?.intensity??60,suffix:'%',onStart:()=>snapshot('프리셋 강도'),onInput:v=>{project.preset.intensity=v;changed()}}));for(const cat of PRESET_CATEGORIES){panel.append(html('div',{class:'mini-heading',text:cat}));const grid=html('div',{class:'preset-grid'});PHOTO_PRESETS.filter(p=>p.category===cat).forEach(p=>{const b=html('button',{class:`preset-card ${project.preset?.id===p.id?'active':''}`});b.innerHTML=`<span class="preset-swatch ${cat.toLowerCase()}"></span><b>${p.name}</b><small>${p.hint||cat}</small>`;b.onclick=()=>{snapshot(`프리셋: ${p.name}`);project.preset={id:p.id,intensity:project.preset?.intensity??60};project.adjustments={...p.values};changed({panelToo:true})};grid.append(b)});panel.append(grid)}}
  function renderAdjust(){sectionTitle('기본 보정','화이트밸런스·노란기·명암·선명도를 비파괴 방식으로 조절합니다.');const wb=html('button',{class:'wide',text:'⚪ 자동 화이트밸런스'});wb.onclick=autoWhiteBalance;panel.append(wb);for(const [key,label,min,max] of ADJUSTMENT_LABELS)panel.append(makeRange({label,min,max,value:project.adjustments[key]||0,onStart:()=>snapshot(label),onInput:v=>{project.adjustments[key]=v;changed()}}));const reset=html('button',{class:'wide danger-ghost',text:'보정값 초기화'});reset.onclick=()=>{snapshot('보정 초기화');project.adjustments={...DEFAULT_ADJUSTMENTS};changed({panelToo:true})};panel.append(reset)}

  function renderEdge(){
    sectionTitle('캐릭터 외곽선','배경 제거가 목적이 아닙니다. Glow에 사용할 캐릭터 실루엣을 자동 초안 + 수동 점/곡선으로 정확하게 확정합니다.')
    const aiBox=html('div',{class:'ai-edge-box'}),ai=html('button',{class:'wide primary',text:'🧠 AI 정밀 캐릭터 인식'});ai.onclick=()=>aiSelect(ai);aiBox.append(ai,html('small',{text:'일반 배경 사진에서 캐릭터 실루엣 초안을 생성합니다. 최초 1회는 AI 모델 다운로드 때문에 시간이 걸릴 수 있습니다.'}));panel.append(aiBox)
    const quick=html('div',{class:'button-grid'}),auto=html('button',{text:'⚡ 빠른 자동 초안'}),wand=html('button',{text:'🪄 마법봉'}),add=html('button',{text:'+ 브러시'}),sub=html('button',{text:'− 브러시'});auto.onclick=autoSelect;wand.onclick=()=>setTool('wand');add.onclick=()=>setTool('mask-add');sub.onclick=()=>setTool('mask-remove');quick.append(auto,wand,add,sub);panel.append(quick)
    const manual=html('div',{class:'manual-edge-card'});manual.append(html('b',{text:'수동 외곽선 — 점과 선으로 직접 지정'}));const tools=html('div',{class:'button-grid'});manual.append(tools)
    for(const [t,n] of [['polygon','● Polygon 점선'],['bezier','⌁ Curve 곡선']]){const b=html('button',{class:activeTool===t?'active':'',text:n});b.onclick=()=>{project.manualPath.mode=t;setTool(t);renderPanel()};tools.append(b)}
    const actions=html('div',{class:'button-grid'}),undoPoint=html('button',{text:'마지막 점 지우기'}),apply=html('button',{class:'primary',text:'외곽선 적용'}),clear=html('button',{text:'점 전체 지우기'});undoPoint.onclick=()=>{if(project.manualPath.points.length){snapshot('외곽선 점 삭제');project.manualPath.points.pop();project.manualPath.closed=false;scheduleRender();renderPanel()}};apply.onclick=applyManualPath;clear.onclick=()=>{snapshot('수동 외곽선 초기화');project.manualPath.points=[];project.manualPath.closed=false;scheduleRender();renderPanel()};actions.append(undoPoint,apply,clear);manual.append(actions)
    const snap=html('label',{class:'switch-row'});snap.innerHTML=`<span>경계 자동 붙이기 (Magnetic)</span><input type="checkbox" ${project.manualPath.edgeSnap?'checked':''}>`;snap.querySelector('input').onchange=e=>{project.manualPath.edgeSnap=e.target.checked};manual.append(snap,makeRange({label:'Snap 반경',min:2,max:40,value:project.manualPath.snapRadius,onStart:()=>snapshot('Snap 반경'),onInput:v=>project.manualPath.snapRadius=v}),html('div',{class:'info-box',text:'Tip: 캐릭터 바깥선을 따라 대략 클릭하면 주변의 색/명암 경계를 찾아 점을 붙입니다. 밝은 하늘·머리카락처럼 자동 감지가 약한 구간은 확대 후 점을 추가하세요.'}));panel.append(manual)
    panel.append(makeRange({label:'마법봉 Tolerance',min:1,max:100,value:project.maskSettings.tolerance,onStart:()=>snapshot('Tolerance'),onInput:v=>project.maskSettings.tolerance=v}),makeRange({label:'Edge Feather',min:0,max:14,value:project.maskSettings.feather,onStart:()=>snapshot('Feather'),onInput:v=>project.maskSettings.feather=v}),makeRange({label:'브러시 크기',min:4,max:180,value:project.maskSettings.brushSize,onStart:()=>snapshot('브러시 크기'),onInput:v=>project.maskSettings.brushSize=v}))
    const views=html('div',{class:'view-button-grid'});[['original','원본'],['mask','마스크'],['edge','외곽선'],['rim','Rim만'],['halo','Halo만'],['sparkle','반짝이만'],['lighting','전체 빛'],['final','최종 합성']].forEach(([v,n])=>{const b=html('button',{class:project.canvas.viewMode===v?'active':'',text:n});b.onclick=()=>{project.canvas.viewMode=v;syncViewButtons();scheduleRender();renderPanel()};views.append(b)});panel.append(html('div',{class:'mini-heading',text:'검수 모드'}),views)
    const cut=html('label',{class:'switch-row'});cut.innerHTML=`<span>실제 배경 제거(선택 사항)</span><input type="checkbox" ${mainLayer()?.cutout?'checked':''}>`;cut.querySelector('input').onchange=e=>{const l=mainLayer();if(!l)return;snapshot('배경 제거');l.cutout=e.target.checked;changed()};panel.append(cut)
  }

  function renderLighting(){
    sectionTitle('Directional Rim Light','균일한 외곽선이 아니라 실제 빛 방향을 따라 Rim Light + Halo + Sparkle을 별도 레이어처럼 합성합니다.')
    const tog=html('label',{class:'switch-row'});tog.innerHTML=`<span>캐릭터 라이팅 사용</span><input type="checkbox" ${project.lighting.enabled?'checked':''}>`;tog.querySelector('input').onchange=e=>{snapshot('캐릭터 라이팅');project.lighting.enabled=e.target.checked;changed()};panel.append(tog)
    const grid=html('div',{class:'glow-preset-grid'});Object.entries(LIGHT_PRESETS).forEach(([name,v])=>{const b=html('button',{text:name});b.style.background=`linear-gradient(135deg,${v.rimColor},${v.haloColor})`;b.onclick=()=>{snapshot(`Light ${name}`);Object.assign(project.lighting,v,{enabled:true,preset:name});changed({panelToo:true})};grid.append(b)});panel.append(grid)
    panel.append(html('div',{class:'mini-heading',text:'빛 방향'}))
    const compass=html('div',{class:'light-compass'});[[225,'↖'],[270,'↑'],[315,'↗'],[180,'←'],[0,'→'],[135,'↙'],[90,'↓'],[45,'↘']].forEach(([angle,label])=>{const b=html('button',{text:label,class:Math.abs(((project.lighting.angle-angle+540)%360)-180)<3?'active':''});b.onclick=()=>{snapshot('빛 방향');project.lighting.angle=angle;project.lighting.enabled=true;changed({panelToo:true})};compass.append(b)});panel.append(compass)
    panel.append(makeRange({label:'빛 방향 각도',min:0,max:359,value:project.lighting.angle||0,suffix:'°',onStart:()=>snapshot('빛 방향'),onInput:v=>{project.lighting.angle=v;project.lighting.enabled=true;changed()}}),makeRange({label:'빛이 닿는 범위',min:20,max:180,value:project.lighting.range||92,suffix:'°',onStart:()=>snapshot('빛 범위'),onInput:v=>{project.lighting.range=v;changed()}}),makeRange({label:'방향 집중도',min:.5,max:3,step:.05,value:project.lighting.focus||1.7,onStart:()=>snapshot('빛 집중도'),onInput:v=>{project.lighting.focus=v;changed()}}),makeRange({label:'빛 결 자연스러움',min:0,max:.35,step:.01,value:project.lighting.breakup??.12,onStart:()=>snapshot('빛 결'),onInput:v=>{project.lighting.breakup=v;changed()}}))
    panel.append(html('div',{class:'mini-heading',text:'Rim Light · 캐릭터 표면 경계광'}),makeColor('Rim 색',project.lighting.rimColor,v=>{project.lighting.rimColor=v;project.lighting.enabled=true;changed()},()=>snapshot('Rim 색')),makeRange({label:'Rim 폭',min:.5,max:8,step:.1,value:project.lighting.rimWidth,onStart:()=>snapshot('Rim 폭'),onInput:v=>{project.lighting.rimWidth=v;changed()}}),makeRange({label:'Rim 밝기',min:0,max:100,value:project.lighting.rimOpacity,onStart:()=>snapshot('Rim 밝기'),onInput:v=>{project.lighting.rimOpacity=v;changed()}}),makeRange({label:'Rim 부드러움',min:0,max:3,step:.1,value:project.lighting.rimSoftness,onStart:()=>snapshot('Rim 부드러움'),onInput:v=>{project.lighting.rimSoftness=v;changed()}}))
    panel.append(html('div',{class:'mini-heading',text:'Halo · 배경으로 퍼지는 빛'}),makeColor('Halo 색',project.lighting.haloColor,v=>{project.lighting.haloColor=v;project.lighting.enabled=true;changed()},()=>snapshot('Halo 색')),makeRange({label:'Halo 폭',min:2,max:28,value:project.lighting.haloWidth,onStart:()=>snapshot('Halo 폭'),onInput:v=>{project.lighting.haloWidth=v;changed()}}),makeRange({label:'Halo 불투명도',min:0,max:35,value:project.lighting.haloOpacity,onStart:()=>snapshot('Halo 밝기'),onInput:v=>{project.lighting.haloOpacity=v;changed()}}),makeRange({label:'Halo Softness',min:2,max:24,value:project.lighting.haloSoftness,onStart:()=>snapshot('Halo Softness'),onInput:v=>{project.lighting.haloSoftness=v;changed()}}))
    panel.append(html('div',{class:'mini-heading',text:'Sparkle Edge · 일부 포인트만 반짝이기'}),makeColor('반짝이 색',project.lighting.sparkleColor,v=>{project.lighting.sparkleColor=v;changed()},()=>snapshot('Sparkle 색')),makeRange({label:'반짝이 개수',min:0,max:20,value:project.lighting.sparkleCount,onStart:()=>snapshot('반짝이 개수'),onInput:v=>{project.lighting.sparkleCount=v;changed()}}),makeRange({label:'반짝이 크기',min:.8,max:7,step:.2,value:project.lighting.sparkleSize,onStart:()=>snapshot('반짝이 크기'),onInput:v=>{project.lighting.sparkleSize=v;changed()}}))
    const views=html('div',{class:'view-button-grid'});[['rim','Rim만'],['halo','Halo만'],['sparkle','Sparkle만'],['lighting','전체 빛'],['final','최종 합성']].forEach(([v,n])=>{const b=html('button',{text:n});b.onclick=()=>{project.canvas.viewMode=v;syncViewButtons();scheduleRender()};views.append(b)});panel.append(views,html('div',{class:'info-box',text:project.maskDataUrl?'✓ 외곽 마스크가 있습니다. 빛은 외곽선 법선 방향과 광원 방향을 비교해서 일부 가장자리에만 생성됩니다.':'먼저 외곽선 탭에서 캐릭터 경계를 자동 또는 Polygon/Curve로 지정해주세요.'}))
  }

  function renderBackground(){
    sectionTitle('배경 만들기','단색·그라데이션·체크·땡땡이·하트/별 패턴 또는 직접 첨부한 사진을 배경 레이어로 사용합니다. 모든 패턴 색상과 크기/각도를 바꿀 수 있습니다.')
    const grid=html('div',{class:'button-grid'}),color=html('button',{text:'+ 단색'}),grad=html('button',{text:'+ 그라데이션'}),pattern=html('button',{text:'+ 패턴'}),image=html('button',{text:'+ 배경 사진'})
    color.onclick=()=>addBackground('color');grad.onclick=()=>addBackground('gradient');pattern.onclick=()=>addBackground('pattern');image.onclick=addBackgroundImage;grid.append(color,grad,pattern,image);panel.append(grid)
    const bgLayers=project.layers.filter(l=>l.type==='background'||l.role==='background')
    for(const l of bgLayers){const b=html('button',{class:`asset-row ${project.selectedLayerId===l.id?'active':''}`});b.innerHTML=`<span>▧</span><b>${l.name}</b>`;b.onclick=()=>{project.selectedLayerId=l.id;renderLayerList();renderLayerProps();renderPanel()};panel.append(b)}
    const l=selectedLayer();if(!l||l.type!=='background')return
    const b=l.background||(l.background={type:'color',colorA:'#efeaff'})
    panel.append(html('div',{class:'mini-heading',text:'선택 배경 디자인'}),makeSelect('배경 종류',[{value:'color',label:'단색'},{value:'gradient',label:'그라데이션'},{value:'pattern',label:'패턴'}],b.type||b.mode||'color',v=>{snapshot('배경 종류');b.type=v;b.mode=v;changed({panelToo:true})}))
    if((b.type||b.mode)==='color')panel.append(makeColor('배경색',b.colorA||b.color||'#efeaff',v=>{b.colorA=b.color=v;changed()},()=>snapshot('배경색')))
    if((b.type||b.mode)==='gradient')panel.append(makeSelect('그라데이션',[{value:'linear',label:'선형'},{value:'radial',label:'원형'},{value:'conic',label:'원뿔형'}],b.gradientType||'linear',v=>{b.gradientType=v;changed()}),makeColor('색상 A',b.colorA||'#cbc3ff',v=>{b.colorA=v;changed()},()=>snapshot('색상 A')),makeColor('색상 B',b.colorB||'#ffd4e6',v=>{b.colorB=v;changed()},()=>snapshot('색상 B')),makeColor('색상 C',b.colorC||'#fff3fa',v=>{b.colorC=v;changed()},()=>snapshot('색상 C')),makeRange({label:'각도',min:0,max:359,value:b.angle||135,suffix:'°',onStart:()=>snapshot('그라데이션 각도'),onInput:v=>{b.angle=v;changed()}}))
    if((b.type||b.mode)==='pattern')panel.append(makeSelect('패턴',PATTERN_OPTIONS.map(([value,label])=>({value,label})),b.pattern||'gingham',v=>{b.pattern=v;changed()}),makeColor('바탕색',b.colorA||'#ffffff',v=>{b.colorA=v;changed()},()=>snapshot('패턴 바탕')),makeColor('무늬색 A',b.colorB||'#d7ceff',v=>{b.colorB=v;changed()},()=>snapshot('패턴 색')),makeColor('무늬색 B',b.colorC||'#f8d7e7',v=>{b.colorC=v;changed()},()=>snapshot('패턴 색')),makeRange({label:'무늬 크기',min:6,max:120,value:b.size||28,onStart:()=>snapshot('패턴 크기'),onInput:v=>{b.size=v;changed()}}),makeRange({label:'간격',min:0,max:60,value:b.gap??4,onStart:()=>snapshot('패턴 간격'),onInput:v=>{b.gap=v;changed()}}),makeRange({label:'각도',min:0,max:359,value:b.angle||0,suffix:'°',onStart:()=>snapshot('패턴 각도'),onInput:v=>{b.angle=v;changed()}}),makeRange({label:'무늬 불투명도',min:5,max:100,value:b.opacity??100,suffix:'%',onStart:()=>snapshot('패턴 투명도'),onInput:v=>{b.opacity=v;changed()}}))
  }
  async function renderFrames(){sectionTitle('내 프레임','기본 저품질 프레임은 없습니다. 직접 가져온 PNG/WebP/SVG 프레임이 브라우저에 자동 저장됩니다.');const up=html('button',{class:'wide primary soft',text:'+ 프레임 불러오기'});up.onclick=importFrame;panel.append(up);frameAssets=await getAssets('frame').catch(()=>[]);const grid=html('div',{class:'asset-grid'});if(!frameAssets.length)grid.append(html('div',{class:'empty-small',text:'저장된 프레임이 없습니다.'}));for(const a of frameAssets){const card=html('div',{class:'asset-card'});card.innerHTML=`<img src="${a.dataUrl}" alt=""><span>${a.name}</span><button class="asset-del">×</button>`;card.querySelector('img').onclick=()=>addFrameAsset(a);card.querySelector('span').onclick=()=>addFrameAsset(a);card.querySelector('.asset-del').onclick=async e=>{e.stopPropagation();await deleteAsset(a.id);renderFrames()};grid.append(card)}panel.append(grid)}
  function renderText(){sectionTitle('텍스트 디자인','문자별 회전·크기·색상·2중 외곽선, 로컬/웹폰트를 지원합니다.');const add=html('button',{class:'wide primary soft',text:'+ 텍스트 추가'}),font=html('button',{class:'wide',text:'+ 웹폰트 / 폰트 파일'});add.onclick=addTextLayer;font.onclick=openFontDialog;panel.append(add,font);const l=selectedLayer();if(!l||l.type!=='text'){panel.append(html('div',{class:'info-box',text:'텍스트 레이어를 선택하면 상세 편집이 나타납니다.'}));return}panel.append(textEditorControls(l))}
  function renderDraw(){sectionTitle('펜 / 하이라이트','그린 선은 독립 레이어이며 모두 Undo 가능합니다.');const tools=html('div',{class:'button-grid'});for(const [t,n] of [['pen','✎ Pen'],['glow-pen','✧ Glow'],['sparkle-pen','✦ Sparkle'],['select','↖ 선택']]){const b=html('button',{class:activeTool===t?'active':'',text:n});b.onclick=()=>{setTool(t);renderPanel()};tools.append(b)}panel.append(tools,makeRange({label:'브러시 크기',min:1,max:80,value:project.brush.size,onStart:()=>snapshot('브러시 크기'),onInput:v=>project.brush.size=v}),makeRange({label:'불투명도',min:5,max:100,value:project.brush.opacity,onStart:()=>snapshot('브러시 투명도'),onInput:v=>project.brush.opacity=v}),makeColor('브러시 색',project.brush.color,v=>project.brush.color=v,()=>snapshot('브러시 색')))}

  function renderExport(){
    sectionTitle('고정 크기 용량 최적화','픽셀 크기는 고정한 채 PNG의 색상/알파를 단계적으로 정리해서 50KB 이하의 가장 높은 품질을 찾습니다. 원본 편집 프로젝트 크기는 바뀌지 않습니다.')
    const info=html('div',{class:'info-box',text:'모바일: 293×248 PNG ≤ 50KB · PC: 195×145 PNG ≤ 50KB. 복잡한 사진은 50KB를 만족하려면 색상 단계가 눈에 띄게 줄 수 있어 결과를 꼭 확인하세요.'})
    const status=html('div',{class:'optimizer-status',text:'아직 최적화를 실행하지 않았습니다.'})
    const mobile=html('button',{class:'wide primary',text:'모바일 293×248 · 50KB 이하'}),pc=html('button',{class:'wide primary soft',text:'PC 195×145 · 50KB 이하'}),batch=html('button',{class:'wide',text:'모바일 + PC 두 버전 저장'})
    mobile.onclick=()=>exportFixedPhoto('mobile',status,mobile);pc.onclick=()=>exportFixedPhoto('pc',status,pc);batch.onclick=async()=>{batch.disabled=true;await exportFixedPhoto('mobile',status,null);await exportFixedPhoto('pc',status,null);batch.disabled=false}
    panel.append(info,mobile,pc,batch,status,html('div',{class:'mini-heading',text:'규칙'}),html('div',{class:'info-box',text:'✓ 출력 Width/Height 잠금\n✓ PNG 유지\n✓ 해상도 자동 축소 금지\n✓ 메타데이터 없이 Canvas에서 재인코딩\n✓ 50KB 미달 시 그 시점에서 즉시 중단'}))
  }
  async function exportFixedPhoto(key,status,button){
    if(!mainLayer()){toast('먼저 사진을 업로드해주세요.','error');return}
    const preset=PHOTO_EXPORT_PRESETS[key];const old=button?.textContent;if(button){button.disabled=true;button.textContent='렌더링 중…'}
    try{
      const c=await renderPhotoProject({...project,canvas:{...project.canvas,viewMode:'final'}},{width:preset.width,height:preset.height,viewMode:'final'})
      const result=await optimizePngFixedSize(c,preset.maxBytes,(p,r)=>{if(status)status.textContent=`${Math.round(p*100)}% · 현재 ${(r.bytes/1024).toFixed(1)}KB · ${r.qualityLabel}`})
      if(!result.metTarget)throw new Error(`${preset.width}×${preset.height} 크기를 유지한 채 50KB 이하로 만들지 못했습니다. 저장을 중단했습니다.`)
      const name=`profile-${key}-${preset.width}x${preset.height}-v2.1.png`;downloadBlob(result.blob,name)
      if(status){status.textContent=`${preset.label}: ${describeOptimizerResult(result)} ✅ 50KB 이하`;status.className='optimizer-status ok'}
      toast(`${preset.label} 최적화 저장 완료`,'success')
    }catch(e){toast(e.message,'error');if(status)status.textContent=`오류: ${e.message}`}
    finally{if(button){button.disabled=false;button.textContent=old}}
  }

  function setTool(t){activeTool=t;updateToolStatus();scheduleRender()}
  function syncViewButtons(){$$('[data-view]',root).forEach(x=>x.classList.toggle('active',x.dataset.view===project.canvas.viewMode))}
  function addBackground(mode){snapshot('배경 추가');const presets={color:{type:'color',mode:'color',colorA:'#efeaff',color:'#efeaff'},gradient:{type:'gradient',mode:'gradient',gradientType:'linear',colorA:'#cbc3ff',colorB:'#ffd4e6',colorC:'#ccecff',angle:135},pattern:{type:'pattern',mode:'pattern',pattern:'gingham',colorA:'#ffffff',colorB:'#d9d1ff',colorC:'#ffd9e8',size:28,gap:4,angle:0,opacity:100}};const l={id:uid('bg'),type:'background',role:'background',name:mode==='gradient'?'Gradient Background':mode==='pattern'?'Pattern Background':'Color Background',visible:true,opacity:1,blend:'source-over',background:presets[mode]||presets.color};project.layers.unshift(l);project.selectedLayerId=l.id;changed({panelToo:true})}
  async function addBackgroundImage(){const f=await filePicker('image/*');if(!f)return;snapshot('배경 사진 추가');const dataUrl=await fileToDataUrl(f),l={id:uid('bgimg'),type:'image',role:'background',name:f.name,visible:true,opacity:1,dataUrl,fit:'cover',filters:{brightness:0,saturation:0,blur:0},transform:{x:0,y:0,scale:1,rotation:0},blend:'source-over'};project.layers.unshift(l);project.selectedLayerId=l.id;changed()}
  async function importFrame(){const f=await filePicker('image/png,image/webp,image/svg+xml,image/jpeg');if(!f)return;const dataUrl=await fileToDataUrl(f),asset={id:uid('frameasset'),kind:'frame',name:f.name,dataUrl,createdAt:Date.now()};await putAsset(asset);toast('프레임을 내 라이브러리에 저장했습니다.','success');addFrameAsset(asset);renderFrames()}
  function addFrameAsset(a){snapshot('프레임 적용');const l={id:uid('frame'),type:'frame',role:'frame',name:a.name,visible:true,opacity:1,dataUrl:a.dataUrl,fit:'contain',transform:{x:0,y:0,scale:1,rotation:0},blend:'source-over'};project.layers.push(l);project.selectedLayerId=l.id;changed()}
  function addTextLayer(){snapshot('텍스트 추가');const l={id:uid('text'),type:'text',name:'Text',visible:true,opacity:1,text:'PROFILE',style:{x:project.canvas.width/2,y:project.canvas.height*.82,fontFamily:'sans-serif',fontSize:64,fontWeight:700,color:'#ffffff',stroke:'#786fb9',strokeWidth:4,stroke2:'#ffffff',strokeWidth2:0,rotation:0,letterSpacing:2,shadowColor:'#00000044',shadowBlur:4,chars:[]}};project.layers.push(l);project.selectedLayerId=l.id;activeTab='text';$$('.tool-rail button',root).forEach(x=>x.classList.toggle('active',x.dataset.tab==='text'));changed({panelToo:true})}
  function textEditorControls(l){const box=html('div',{class:'stack'}),ta=html('textarea',{rows:'2'});ta.value=l.text;ta.onfocus=()=>snapshot('텍스트 내용');ta.oninput=()=>{l.text=ta.value;changed()};box.append(html('label',{class:'field'},[html('span',{text:'내용'}),ta]));const families=fontOptions();box.append(makeSelect('폰트',families,l.style.fontFamily,v=>{snapshot('폰트');l.style.fontFamily=v;changed()}),makeRange({label:'크기',min:8,max:240,value:l.style.fontSize,onStart:()=>snapshot('텍스트 크기'),onInput:v=>{l.style.fontSize=v;changed()}}),makeRange({label:'X',min:0,max:project.canvas.width,value:l.style.x,onStart:()=>snapshot('텍스트 X'),onInput:v=>{l.style.x=v;changed()}}),makeRange({label:'Y',min:0,max:project.canvas.height,value:l.style.y,onStart:()=>snapshot('텍스트 Y'),onInput:v=>{l.style.y=v;changed()}}),makeRange({label:'회전',min:-180,max:180,value:l.style.rotation,onStart:()=>snapshot('텍스트 회전'),onInput:v=>{l.style.rotation=v;changed()}}),makeRange({label:'외곽선 1',min:0,max:20,value:l.style.strokeWidth,onStart:()=>snapshot('외곽선'),onInput:v=>{l.style.strokeWidth=v;changed()}}),makeRange({label:'외곽선 2',min:0,max:28,value:l.style.strokeWidth2||0,onStart:()=>snapshot('외곽선 2'),onInput:v=>{l.style.strokeWidth2=v;changed()}}),makeColor('글자색',l.style.color,v=>{l.style.color=v;changed()},()=>snapshot('글자색')),makeColor('외곽선 1 색',l.style.stroke,v=>{l.style.stroke=v;changed()},()=>snapshot('외곽선색')),makeColor('외곽선 2 색',l.style.stroke2||'#ffffff',v=>{l.style.stroke2=v;changed()},()=>snapshot('외곽선2색')));const idx=html('input',{type:'number',min:1,max:Math.max(1,[...l.text].length),value:1}),charBox=html('div',{class:'subcard'});charBox.append(html('b',{text:'한 글자씩 꾸미기'}),html('label',{class:'field'},[html('span',{text:'글자 번호'}),idx]));const mk=()=>{const i=Math.max(0,Number(idx.value)-1),arr=l.style.chars||(l.style.chars=[]);arr[i]=arr[i]||{};return arr[i]};charBox.append(makeRange({label:'글자 회전',min:-90,max:90,value:0,onStart:()=>snapshot('글자 회전'),onInput:v=>{mk().charRotation=v;changed()}}),makeRange({label:'글자 크기',min:40,max:180,value:100,suffix:'%',onStart:()=>snapshot('글자 크기'),onInput:v=>{mk().charScale=v/100;changed()}}),makeRange({label:'글자 X',min:-100,max:100,value:0,onStart:()=>snapshot('글자 X'),onInput:v=>{mk().offsetX=v;changed()}}),makeRange({label:'글자 Y',min:-100,max:100,value:0,onStart:()=>snapshot('글자 Y'),onInput:v=>{mk().offsetY=v;changed()}}),makeColor('개별 글자색','#ffffff',v=>{mk().color=v;changed()},()=>snapshot('개별 글자색')));box.append(charBox);return box}

  async function openFontDialog(){const choice=prompt('폰트 불러오기\n1 = TTF/OTF/WOFF 파일\n2 = WOFF/WOFF2 URL\n3 = @font-face CSS','1');try{if(choice==='1'){const f=await filePicker('.ttf,.otf,.woff,.woff2,font/*');if(!f)return;const meta=await addFontFromFile(f);await putAsset({id:uid('font'),kind:'font',name:meta.family,family:meta.family,data:meta.data,source:'file',createdAt:Date.now()})}else if(choice==='2'){const url=prompt('WOFF/WOFF2 직접 URL');if(!url)return;const name=prompt('폰트 이름','Custom WebFont');await addFontFromUrl(url,name);await putAsset({id:uid('font'),kind:'font',name,family:name,url,source:'url',createdAt:Date.now()})}else if(choice==='3'){const css=prompt('@font-face CSS를 붙여넣으세요. 폰트 라이선스와 CORS를 확인해주세요.');if(css)injectFontFaceCss(css)}await loadFonts();renderPanel();toast('폰트를 적용했습니다.','success')}catch(e){toast(`폰트 로드 실패: ${e.message}`,'error')}}
  async function loadFonts(){await fontRegistry.init();fontAssets=fontRegistry.list().filter(f=>!f.builtin)}
  async function autoWhiteBalance(){try{const {imageData}=await rasterMain();let r=0,g=0,b=0,n=0,step=Math.max(4,Math.floor(imageData.data.length/4/5000));for(let p=0;p<imageData.width*imageData.height;p+=step){const i=p*4;if(imageData.data[i+3]<30)continue;r+=imageData.data[i];g+=imageData.data[i+1];b+=imageData.data[i+2];n++}r/=n;g/=n;b/=n;snapshot('자동 화이트밸런스');project.adjustments.temperature=Math.round(Math.max(-25,Math.min(25,(b-r)*.12)));project.adjustments.tint=Math.round(Math.max(-20,Math.min(20,(g-(r+b)/2)*-.1)));project.adjustments.yellowReduce=Math.max(project.adjustments.yellowReduce||0,Math.round(Math.max(0,(Math.min(r,g)-b)*.12)));changed({panelToo:true});toast('화이트밸런스를 보정했습니다.','success')}catch(e){toast(e.message,'error')}}
  async function recommendPreset(){try{const {imageData}=await rasterMain();let lum=0,r=0,b=0,n=0,step=Math.max(1,Math.floor(imageData.width*imageData.height/6000));for(let p=0;p<imageData.width*imageData.height;p+=step){const i=p*4;r+=imageData.data[i];b+=imageData.data[i+2];lum+=imageData.data[i]*.2126+imageData.data[i+1]*.7152+imageData.data[i+2]*.0722;n++}lum/=n;r/=n;b/=n;let pid='clean-clear';if(lum<95)pid='night-clear';else if(r-b>14)pid='cool-clear';else if(b-r>12)pid='warm-clear';else if(lum>185)pid='soft-clear';const p=PHOTO_PRESETS.find(x=>x.id===pid);snapshot('스마트 프리셋');project.adjustments={...p.values};project.preset={id:p.id,intensity:60};changed({panelToo:true});toast(`추천: ${p.name} · 60%`,'success')}catch(e){toast(e.message,'error')}}

  function renderLayerList(){layerList.innerHTML='';[...project.layers].reverse().forEach((l,ri)=>{const actual=project.layers.length-1-ri,row=html('div',{class:`layer-row ${l.id===project.selectedLayerId?'active':''}`,draggable:'true'});row.innerHTML=`<button class="vis">${l.visible===false?'○':'●'}</button><span class="layer-icon">${l.type==='text'?'T':l.type==='frame'?'▣':l.type==='background'?'▧':'▦'}</span><b>${l.name}</b><small>${Math.round((l.opacity??1)*100)}%</small>`;row.onclick=e=>{if(e.target.classList.contains('vis'))return;project.selectedLayerId=l.id;renderLayerList();renderLayerProps();if(l.type==='text'){activeTab='text';renderPanel()}};row.querySelector('.vis').onclick=e=>{e.stopPropagation();snapshot('레이어 표시');l.visible=l.visible===false;changed()};row.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',String(actual)));row.addEventListener('dragover',e=>e.preventDefault());row.addEventListener('drop',e=>{e.preventDefault();const from=Number(e.dataTransfer.getData('text/plain')),to=actual;if(from===to)return;snapshot('레이어 순서');const [m]=project.layers.splice(from,1);project.layers.splice(to,0,m);changed()});layerList.append(row)})}
  function renderLayerProps(){layerProps.innerHTML='';const l=selectedLayer();if(!l){layerProps.append(html('div',{class:'empty-small',text:'레이어를 선택하세요.'}));return}const name=html('input',{value:l.name});name.onchange=()=>{snapshot('레이어 이름');l.name=name.value;changed()};layerProps.append(html('label',{class:'field'},[html('span',{text:'이름'}),name]),makeRange({label:'불투명도',min:0,max:100,value:Math.round((l.opacity??1)*100),onStart:()=>snapshot('불투명도'),onInput:v=>{l.opacity=v/100;changed()}}));layerProps.append(makeSelect('블렌드 모드',[{value:'source-over',label:'Normal'},{value:'screen',label:'Screen'},{value:'multiply',label:'Multiply'},{value:'overlay',label:'Overlay'},{value:'soft-light',label:'Soft Light'},{value:'lighter',label:'Add'}],l.blend||'source-over',v=>{snapshot('블렌드 모드');l.blend=v;changed()}));if(l.transform)layerProps.append(makeRange({label:'크기',min:20,max:250,value:Math.round((l.transform.scale||1)*100),suffix:'%',onStart:()=>snapshot('크기'),onInput:v=>{l.transform.scale=v/100;changed()}}),makeRange({label:'X',min:-project.canvas.width,max:project.canvas.width,value:l.transform.x||0,onStart:()=>snapshot('X'),onInput:v=>{l.transform.x=v;changed()}}),makeRange({label:'Y',min:-project.canvas.height,max:project.canvas.height,value:l.transform.y||0,onStart:()=>snapshot('Y'),onInput:v=>{l.transform.y=v;changed()}}),makeRange({label:'회전',min:-180,max:180,value:l.transform.rotation||0,onStart:()=>snapshot('회전'),onInput:v=>{l.transform.rotation=v;changed()}}));if(l.type==='image'&&l.role==='background'){l.filters=l.filters||{brightness:0,saturation:0,blur:0};layerProps.append(makeRange({label:'배경 밝기',min:-60,max:60,value:l.filters.brightness||0,onStart:()=>snapshot('배경 밝기'),onInput:v=>{l.filters.brightness=v;changed()}}),makeRange({label:'배경 채도',min:-80,max:80,value:l.filters.saturation||0,onStart:()=>snapshot('배경 채도'),onInput:v=>{l.filters.saturation=v;changed()}}),makeRange({label:'Depth Blur',min:0,max:30,value:l.filters.blur||0,onStart:()=>snapshot('배경 블러'),onInput:v=>{l.filters.blur=v;changed()}}))}const del=html('button',{class:'wide danger-ghost',text:'레이어 삭제'});del.onclick=()=>{if(l.role==='main'&&!confirm('메인 사진을 삭제할까요?'))return;snapshot('레이어 삭제');project.layers=project.layers.filter(x=>x.id!==l.id);project.selectedLayerId=null;changed({panelToo:true})};layerProps.append(del)}
  function renderHistory(){const el=$('#history-list',root);el.innerHTML='';const labels=history.list().slice(-12).reverse();if(!labels.length)el.append(html('div',{class:'empty-small',text:'변경 기록이 없습니다.'}));labels.forEach((x,i)=>el.append(html('div',{class:'history-row',text:`${i===0?'●':'○'} ${x}`})))}
  function updateToolStatus(){const names={select:'선택/이동',wand:'Magic Wand','mask-add':'마스크 추가 브러시','mask-remove':'마스크 제거 브러시',polygon:'Polygon 수동 외곽선',bezier:'Curve 수동 외곽선',pen:'Pen','glow-pen':'Glow Pen','sparkle-pen':'Sparkle Pen'};$('#toolStatus',root).textContent=names[activeTool]||activeTool}

  function scheduleRender(){const seq=++renderSeq;requestAnimationFrame(async()=>{if(!destroyed&&seq===renderSeq)await renderCanvas(seq)})}
  async function renderCanvas(seq){
    const max=920,scale=Math.min(1,max/Math.max(project.canvas.width,project.canvas.height)),w=Math.max(220,Math.round(project.canvas.width*scale)),h=Math.max(220,Math.round(project.canvas.height*scale));canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.fillStyle='#202229';ctx.fillRect(0,0,w,h)
    if(compare&&mainLayer()){try{const im=await loadImage(mainLayer().dataUrl);drawImageFit(ctx,im,w,h,'cover',{})}catch{}return}
    try{const out=await renderPhotoProject(project,{width:w,height:h,viewMode:project.canvas.viewMode});if(seq!==renderSeq)return;ctx.clearRect(0,0,w,h);ctx.drawImage(out,0,0);drawManualPathOverlay(ctx,w,h)}catch(e){console.warn(e)}
    $('.drop-hint',stage).style.display=mainLayer()?'none':'flex';$('#canvasInfo',root).textContent=`${project.canvas.width} × ${project.canvas.height} · Preview ${w} × ${h}`
  }
  function drawManualPathOverlay(ctx,w,h){const pts=project.manualPath?.points||[];if(!pts.length||!['polygon','bezier'].includes(activeTool))return;ctx.save();ctx.strokeStyle='#6df6ff';ctx.fillStyle='#ffffff';ctx.lineWidth=2;ctx.shadowColor='#000';ctx.shadowBlur=3;ctx.beginPath();pts.forEach((p,i)=>{const x=p.x*w,y=p.y*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});if(project.manualPath.closed)ctx.closePath();ctx.stroke();pts.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x*w,p.y*h,i===0?5:4,0,Math.PI*2);ctx.fillStyle=i===0?'#ffde7d':'#ffffff';ctx.fill()});ctx.restore()}
  function canvasPoint(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*project.canvas.width,y:(e.clientY-r.top)/r.height*project.canvas.height,px:(e.clientX-r.left)/r.width,py:(e.clientY-r.top)/r.height}}
  function nearestManualPoint(p){const pts=project.manualPath.points;let bi=-1,bd=18;for(let i=0;i<pts.length;i++){const d=Math.hypot((pts[i].x-p.px)*canvas.clientWidth,(pts[i].y-p.py)*canvas.clientHeight);if(d<bd){bd=d;bi=i}}return bi}
  async function addPathPoint(p){let x=p.x,y=p.y;if(project.manualPath.edgeSnap){edgeSource=edgeSource||await rasterMain();const q=snapPointToEdge(edgeSource.imageData,x,y,project.manualPath.snapRadius);x=q.x;y=q.y}project.manualPath.points.push({x:x/project.canvas.width,y:y/project.canvas.height});project.manualPath.closed=false;scheduleRender();renderPanel()}
  canvas.addEventListener('pointerdown',async e=>{if(!mainLayer()&&activeTool!=='select')return;const p=canvasPoint(e)
    if(activeTool==='wand'){await useMagicWand(p.x,p.y);setTool('select');return}
    if(activeTool==='polygon'||activeTool==='bezier'){const ni=nearestManualPoint(p);if(ni>=0){dragPoint=ni;canvas.setPointerCapture(e.pointerId);return}snapshot('외곽선 점 추가');await addPathPoint(p);return}
    if(activeTool==='mask-add'||activeTool==='mask-remove'){snapshot(activeTool==='mask-add'?'마스크 추가':'마스크 제거');maskDrawing=true;canvas.setPointerCapture(e.pointerId);await paintMask(p);return}
    if(['pen','glow-pen','sparkle-pen'].includes(activeTool)){let l=selectedLayer();if(!l||l.type!=='drawing'){snapshot('그리기 레이어');l={id:uid('draw'),type:'drawing',name:'Drawing',visible:true,opacity:1,strokes:[]};project.layers.push(l);project.selectedLayerId=l.id}drawingStroke={color:project.brush.color,size:project.brush.size,opacity:project.brush.opacity/100,glow:activeTool!=='pen',sparkle:activeTool==='sparkle-pen',points:[p]};l.strokes.push(drawingStroke);canvas.setPointerCapture(e.pointerId);scheduleRender();return}
    const l=selectedLayer();if(l?.transform){snapshot('레이어 이동');moving={layer:l,start:p,ox:l.transform.x||0,oy:l.transform.y||0};canvas.setPointerCapture(e.pointerId)}})
  canvas.addEventListener('pointermove',async e=>{const p=canvasPoint(e);if(dragPoint>=0){project.manualPath.points[dragPoint]={x:p.x/project.canvas.width,y:p.y/project.canvas.height};scheduleRender()}else if(maskDrawing)await paintMask(p);else if(drawingStroke){drawingStroke.points.push(p);scheduleRender()}else if(moving){moving.layer.transform.x=moving.ox+(p.x-moving.start.x);moving.layer.transform.y=moving.oy+(p.y-moving.start.y);scheduleRender();renderLayerProps()}})
  canvas.addEventListener('pointerup',()=>{if(dragPoint>=0){snapshot('외곽선 점 이동');dragPoint=-1;autosave()}if(maskDrawing){maskDrawing=false;project.maskDataUrl=maskEditCanvas.toDataURL('image/png');changed()}if(drawingStroke){drawingStroke=null;changed()}if(moving){moving=null;changed()}})
  async function paintMask(p){const c=await ensureMaskCanvas(),ctx=c.getContext('2d');ctx.save();ctx.globalCompositeOperation=activeTool==='mask-remove'?'destination-out':'source-over';ctx.fillStyle='#fff';ctx.globalAlpha=.9;ctx.beginPath();ctx.arc(p.x,p.y,project.maskSettings.brushSize/2,0,Math.PI*2);ctx.fill();ctx.restore();project.maskDataUrl=c.toDataURL('image/png');scheduleRender()}
  stage.addEventListener('dragover',e=>e.preventDefault());stage.addEventListener('drop',async e=>{e.preventDefault();const f=e.dataTransfer.files?.[0];if(f?.type.startsWith('image/'))await setMainPhoto(f)})
  async function exportImage(type){if(!mainLayer()){toast('먼저 사진을 업로드해주세요.','error');return}try{const c=await renderPhotoProject({...project,canvas:{...project.canvas,viewMode:'final'}},{width:project.canvas.width,height:project.canvas.height,viewMode:'final'});c.toBlob(blob=>{if(blob){downloadBlob(blob,`profile-retouch-v2.1.${type==='png'?'png':'jpg'}`);toast(`${type.toUpperCase()} 저장 완료`,'success')}},type==='png'?'image/png':'image/jpeg',.96)}catch(e){toast(e.message,'error')}}
  function onKey(e){const tag=e.target?.tagName?.toLowerCase();if(['input','textarea','select'].includes(tag)&&!(e.ctrlKey||e.metaKey))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();const p=e.shiftKey?history.redo(project):history.undo(project);if(p)setProject(p)}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();const p=history.redo(project);if(p)setProject(p)}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProjectFile(project)}else if(e.key.toLowerCase()==='w'&&!e.ctrlKey)setTool('wand');else if(e.key.toLowerCase()==='p'&&!e.ctrlKey){project.manualPath.mode='polygon';setTool('polygon');activeTab='edge';renderPanel()}else if(e.key.toLowerCase()==='c'&&!e.ctrlKey){project.manualPath.mode='bezier';setTool('bezier');activeTab='edge';renderPanel()}else if(e.key.toLowerCase()==='b'&&!e.ctrlKey){setTool('pen');activeTab='draw';renderPanel()}else if(e.key.toLowerCase()==='t'&&!e.ctrlKey)addTextLayer();else if(e.key==='Delete'){if(['polygon','bezier'].includes(activeTool)&&project.manualPath.points.length){snapshot('외곽선 점 삭제');project.manualPath.points.pop();scheduleRender();renderPanel();return}const l=selectedLayer();if(l&&l.role!=='main'){snapshot('레이어 삭제');project.layers=project.layers.filter(x=>x.id!==l.id);project.selectedLayerId=null;changed()}}}
  async function onPaste(e){const item=[...(e.clipboardData?.items||[])].find(x=>x.type.startsWith('image/'));if(item){const f=item.getAsFile();if(f)await setMainPhoto(f)}}
  async function init(){bindTop();window.addEventListener('keydown',onKey);window.addEventListener('paste',onPaste);await loadFonts();frameAssets=await getAssets('frame').catch(()=>[]);renderPanel();renderLayerList();renderLayerProps();renderHistory();updateToolStatus();syncViewButtons();scheduleRender();autosave()}
  init();return {destroy(){destroyed=true;window.removeEventListener('keydown',onKey);window.removeEventListener('paste',onPaste)}}
}
